export {
  DEFAULT_ERROR_LABELS_EN,
  DEFAULT_ERROR_LABELS_ZH,
  DEFAULT_MAX_RECOVERY_ATTEMPTS,
  PERMISSION_ERROR_CODES,
  buildAutoRecoveryContinueMessage,
  buildStaleTurnFallbackContinueMessage,
  buildExpandDetail,
  buildPrematureStopRecoveryUserMessage,
  buildRecoveryExhaustedGuide,
  classifyRecoveryExhaustedCategory,
  formatHandlingNotice,
  formatUserFacingNotice,
  formatUserFacingSessionError,
  formatUserFacingToolError,
  getErrorHints,
  getTechnicalToolErrorDetail,
  hasHardToolFailure,
  isAgentRecoveryBoilerplate,
  isBareTransientNetworkErrorLeak,
  isBareTransientNetworkErrorBody,
  shouldHideBareUserVisibleError,
  sanitizeUserVisibleErrorText,
  isEngineToolHardStopLeak,
  isInfrastructureDisconnectMessage,
  isPermissionErrorCode,
  isRecoverableToolError,
  isRecoverableToolFailureMessage,
  isTransientNetworkErrorMessage,
  looksLikeTaskDelivered,
  shouldAutoContinueAfterAssistantText,
  shouldAutoContinueAfterIncompleteDeliverableStop,
  shouldAutoContinueAfterTurnOutcome,
  isHardTurnCompleteStop,
  userGoalRequestsDirectStart,
  userGoalImpliesDeliverable,
  isContinuationOnlyUserText,
  shouldHideRecoveryBubble,
  isDegenerateUserVisibleAssistantFragment,
  isAssistantGiveUpStopBubble,
  isTransientPartialRestartNarration,
  shouldShowNetworkRetryLabel,
  stripRecoverySection,
  stripAgentRecoveryBoilerplateLines,
  stripUserFacingRecoveryCopyLines,
  isUserFacingRecoveryCopyLine,
  isProviderArrearageMessage,
  isSessionBusyInternalError,
} from "../../../src/agent/errors/userFacingErrors.ts";

export type {
  NoticeSeverity,
  RecoveryExhaustedCategory,
  TurnCompleteOutcome,
  UserFacingErrorLabels,
  UserFacingNotice,
} from "../../../src/agent/errors/userFacingErrors.ts";
