#!/usr/bin/env bash
# PD-SAAS-FORK: 一键合并云端性能/缓存 .env（不覆盖 JWT/数据库/API Key）
#
# 用法（ECS 上，与 upgrade.sh 同目录 /opt/nova-ai-studio/）:
#   sudo bash /opt/nova-ai-studio/apply-cloud-perf-env.sh
#
# 本机打包后脚本在 dist-release/apply-cloud-perf-env.sh（与 upgrade.sh 同级）；
# npm run pack:deploy:upload 会上传到 OSS …/nova-ai-studio/apply-cloud-perf-env.sh
# 手工上传 OSS 须 LF 换行，否则 Linux 报 set: pipefail 错误。
set -euo pipefail

INSTALL_ROOT="${INSTALL_ROOT:-/opt/nova-ai-studio}"
ENV_FILE="${ENV_FILE:-$INSTALL_ROOT/.env}"
NO_RESTART=0
PRINT_EXPORT_FLAGS=0
PILOTDECK_EXPORT_SNAPSHOT_V2="${PILOTDECK_EXPORT_SNAPSHOT_V2:-0}"
PILOTDECK_UI_DELIVERABLE_CERTIFICATE="${PILOTDECK_UI_DELIVERABLE_CERTIFICATE:-0}"
PILOTDECK_UI_EXPORT_SNAPSHOT_V2="${PILOTDECK_UI_EXPORT_SNAPSHOT_V2:-0}"
PILOTDECK_UI_EXPORT_USER_AUDIT_MODES="${PILOTDECK_UI_EXPORT_USER_AUDIT_MODES:-0}"
# PD-SAAS-FORK: P0-1 one tri-state rollout key plus exact-slug canaries.
PILOTDECK_CAPABILITY_SCOPE_V2="${PILOTDECK_CAPABILITY_SCOPE_V2:-shadow}"
PILOTDECK_QUALITY_CANARY_SLUGS="${PILOTDECK_QUALITY_CANARY_SLUGS:-mkt-last30days,ala-strategy-advisor}"
# PD-SAAS-FORK P0-2: cloud starts off and exact canary lists start empty.
PILOTDECK_GOAL_QUALITY_CONTRACT="${PILOTDECK_GOAL_QUALITY_CONTRACT:-shadow}"
PILOTDECK_GOAL_QUALITY_CANARY_SLUGS="${PILOTDECK_GOAL_QUALITY_CANARY_SLUGS:-}"
PILOTDECK_GOAL_QUALITY_CANARY_TENANTS="${PILOTDECK_GOAL_QUALITY_CANARY_TENANTS:-}"
# PD-SAAS-FORK workbench yield: brief/infer/sequential shadow-first (no soft-pass)
PILOTDECK_DELIVERABLE_BRIEF_CONTRACT="${PILOTDECK_DELIVERABLE_BRIEF_CONTRACT:-shadow}"
PILOTDECK_INFER_CAPABILITY_CONTEXT="${PILOTDECK_INFER_CAPABILITY_CONTEXT:-shadow}"
PILOTDECK_SEQUENTIAL_DELIVERABLES="${PILOTDECK_SEQUENTIAL_DELIVERABLES:-shadow}"
PILOTDECK_TRY_PROMPT_CONTRACT_V2="${PILOTDECK_TRY_PROMPT_CONTRACT_V2:-1}"
# PD-SAAS-FORK P0-6: cloud is fail-safe off until explicitly promoted.
PILOTDECK_OFFICIAL_MEDIA_V2="${PILOTDECK_OFFICIAL_MEDIA_V2:-off}"
# PD-SAAS-FORK VAP: Visual Asset Platform (R2 shadow — 20260802 hardening).
PILOTDECK_VISUAL_ASSET_PLATFORM="${PILOTDECK_VISUAL_ASSET_PLATFORM:-shadow}"
PILOTDECK_DISCOVER_VISUAL_ASSETS="${PILOTDECK_DISCOVER_VISUAL_ASSETS:-1}"
PILOTDECK_VISUAL_ASSET_PREP="${PILOTDECK_VISUAL_ASSET_PREP:-1}"
PILOTDECK_AUTO_RESOLVE_VISUAL_ASSETS="${PILOTDECK_AUTO_RESOLVE_VISUAL_ASSETS:-1}"
PILOTDECK_VISUAL_BINDING_AUDIT="${PILOTDECK_VISUAL_BINDING_AUDIT:-shadow}"
PILOTDECK_VAP_BIND_BEFORE_WRITE="${PILOTDECK_VAP_BIND_BEFORE_WRITE:-1}"
PILOTDECK_VAP_OFFICIAL_FIRST="${PILOTDECK_VAP_OFFICIAL_FIRST:-1}"
PILOTDECK_VAP_DISCOVER_PARALLEL="${PILOTDECK_VAP_DISCOVER_PARALLEL:-1}"
PILOTDECK_VAP_DIRECT_IMAGE_URL="${PILOTDECK_VAP_DIRECT_IMAGE_URL:-1}"
PILOTDECK_VAP_FORCE_LADDER="${PILOTDECK_VAP_FORCE_LADDER:-1}"
PILOTDECK_VAP_OUTBOUND_MAX="${PILOTDECK_VAP_OUTBOUND_MAX:-4}"
PILOTDECK_VAP_QUERY_PACK="${PILOTDECK_VAP_QUERY_PACK:-generic}"
PILOTDECK_VAP_CRAWLER_SIDECAR="${PILOTDECK_VAP_CRAWLER_SIDECAR:-off}"
PILOTDECK_VAP_LIVE_CAPTURE="${PILOTDECK_VAP_LIVE_CAPTURE:-1}"
PILOTDECK_VAP_VISION_LOCATE="${PILOTDECK_VAP_VISION_LOCATE:-off}"
# PD-SAAS-FORK P0-7: unified content quality is independently rollbackable.
PILOTDECK_CONTENT_QUALITY_V2="${PILOTDECK_CONTENT_QUALITY_V2:-off}"
# PD-SAAS-FORK: product marketing site (SEO/GEO) — production default on
PILOTDECK_MARKETING_SITE="${PILOTDECK_MARKETING_SITE:-1}"
PILOTDECK_MARKETING_CONTACT="${PILOTDECK_MARKETING_CONTACT:-1}"
PILOTDECK_REGISTER_INVITE_CODE="${PILOTDECK_REGISTER_INVITE_CODE:-1}"
PILOTDECK_MARKETING_ANALYTICS="${PILOTDECK_MARKETING_ANALYTICS:-1}"
PILOTDECK_SHOWCASE_SITE="${PILOTDECK_SHOWCASE_SITE:-on}"
PILOTDECK_SHOWCASE_ADMIN="${PILOTDECK_SHOWCASE_ADMIN:-shadow}"
PILOTDECK_MARKETING_I18N="${PILOTDECK_MARKETING_I18N:-1}"
PILOTDECK_MARKETING_PAGES_CMS="${PILOTDECK_MARKETING_PAGES_CMS:-1}"

for arg in "$@"; do
  case "$arg" in
    --no-restart) NO_RESTART=1 ;;
    --print-export-flags) PRINT_EXPORT_FLAGS=1 ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *) echo "未知参数: $arg" >&2; exit 1 ;;
  esac
done

for key in \
  PILOTDECK_EXPORT_SNAPSHOT_V2 \
  PILOTDECK_UI_DELIVERABLE_CERTIFICATE \
  PILOTDECK_UI_EXPORT_SNAPSHOT_V2 \
  PILOTDECK_UI_EXPORT_USER_AUDIT_MODES; do
  value="${!key}"
  case "$value" in
    0|1|true|false|on|off) ;;
    *)
      echo "[apply-perf] ${key}=${value} 非法；仅允许 0/1/true/false/on/off" >&2
      exit 1
      ;;
  esac
done

if [[ ! "$PILOTDECK_CAPABILITY_SCOPE_V2" =~ ^(off|shadow|enforce)$ ]]; then
  echo "[apply-perf] PILOTDECK_CAPABILITY_SCOPE_V2=${PILOTDECK_CAPABILITY_SCOPE_V2} 非法；仅允许 off/shadow/enforce" >&2
  exit 1
fi

if [[ ! "$PILOTDECK_GOAL_QUALITY_CONTRACT" =~ ^(off|shadow|enforce)$ ]]; then
  echo "[apply-perf] PILOTDECK_GOAL_QUALITY_CONTRACT=${PILOTDECK_GOAL_QUALITY_CONTRACT} 非法；仅允许 off/shadow/enforce" >&2
  exit 1
fi

if [[ ! "$PILOTDECK_DELIVERABLE_BRIEF_CONTRACT" =~ ^(off|shadow|enforce)$ ]]; then
  echo "[apply-perf] PILOTDECK_DELIVERABLE_BRIEF_CONTRACT=${PILOTDECK_DELIVERABLE_BRIEF_CONTRACT} 非法；仅允许 off/shadow/enforce" >&2
  exit 1
fi

if [[ ! "$PILOTDECK_INFER_CAPABILITY_CONTEXT" =~ ^(off|shadow|enforce)$ ]]; then
  echo "[apply-perf] PILOTDECK_INFER_CAPABILITY_CONTEXT=${PILOTDECK_INFER_CAPABILITY_CONTEXT} 非法；仅允许 off/shadow/enforce" >&2
  exit 1
fi

if [[ ! "$PILOTDECK_SEQUENTIAL_DELIVERABLES" =~ ^(off|shadow|enforce|0|1|true|false|on)$ ]]; then
  echo "[apply-perf] PILOTDECK_SEQUENTIAL_DELIVERABLES=${PILOTDECK_SEQUENTIAL_DELIVERABLES} 非法；仅允许 off/shadow/enforce/0/1" >&2
  exit 1
fi

if [[ ! "$PILOTDECK_OFFICIAL_MEDIA_V2" =~ ^(off|shadow|enforce)$ ]]; then
  echo "[apply-perf] PILOTDECK_OFFICIAL_MEDIA_V2=${PILOTDECK_OFFICIAL_MEDIA_V2} 非法；仅允许 off/shadow/enforce" >&2
  exit 1
fi

if [[ ! "$PILOTDECK_VISUAL_ASSET_PLATFORM" =~ ^(off|shadow|enforce)$ ]]; then
  echo "[apply-perf] PILOTDECK_VISUAL_ASSET_PLATFORM=${PILOTDECK_VISUAL_ASSET_PLATFORM} 非法；仅允许 off/shadow/enforce" >&2
  exit 1
fi

if [[ ! "$PILOTDECK_VISUAL_BINDING_AUDIT" =~ ^(off|shadow|enforce)$ ]]; then
  echo "[apply-perf] PILOTDECK_VISUAL_BINDING_AUDIT=${PILOTDECK_VISUAL_BINDING_AUDIT} 非法；仅允许 off/shadow/enforce" >&2
  exit 1
fi

if [[ ! "$PILOTDECK_VAP_BIND_BEFORE_WRITE" =~ ^(0|1|true|false|on|off)$ ]]; then
  echo "[apply-perf] PILOTDECK_VAP_BIND_BEFORE_WRITE=${PILOTDECK_VAP_BIND_BEFORE_WRITE} 非法" >&2
  exit 1
fi

if [[ ! "$PILOTDECK_CONTENT_QUALITY_V2" =~ ^(off|shadow|enforce)$ ]]; then
  echo "[apply-perf] PILOTDECK_CONTENT_QUALITY_V2=${PILOTDECK_CONTENT_QUALITY_V2} 非法；仅允许 off/shadow/enforce" >&2
  exit 1
fi

if [[ ! "$PILOTDECK_MARKETING_SITE" =~ ^(0|1|true|false|on|off)$ ]]; then
  echo "[apply-perf] PILOTDECK_MARKETING_SITE=${PILOTDECK_MARKETING_SITE} 非法；仅允许 0/1/true/false/on/off" >&2
  exit 1
fi

if [[ ! "$PILOTDECK_SHOWCASE_SITE" =~ ^(on|off|0|1|true|false)$ ]]; then
  echo "[apply-perf] PILOTDECK_SHOWCASE_SITE=${PILOTDECK_SHOWCASE_SITE} 非法；仅允许 on/off" >&2
  exit 1
fi

if [[ ! "$PILOTDECK_SHOWCASE_ADMIN" =~ ^(off|shadow|enforce)$ ]]; then
  echo "[apply-perf] PILOTDECK_SHOWCASE_ADMIN=${PILOTDECK_SHOWCASE_ADMIN} 非法；仅允许 off/shadow/enforce" >&2
  exit 1
fi

if [[ ! "$PILOTDECK_MARKETING_I18N" =~ ^(0|1|true|false|on|off)$ ]]; then
  echo "[apply-perf] PILOTDECK_MARKETING_I18N=${PILOTDECK_MARKETING_I18N} 非法" >&2
  exit 1
fi

if [[ ! "$PILOTDECK_MARKETING_PAGES_CMS" =~ ^(0|1|true|false|on|off)$ ]]; then
  echo "[apply-perf] PILOTDECK_MARKETING_PAGES_CMS=${PILOTDECK_MARKETING_PAGES_CMS} 非法" >&2
  exit 1
fi

for key in \
  PILOTDECK_MARKETING_CONTACT \
  PILOTDECK_REGISTER_INVITE_CODE \
  PILOTDECK_MARKETING_ANALYTICS; do
  value="${!key}"
  if [[ ! "$value" =~ ^(0|1|true|false|on|off)$ ]]; then
    echo "[apply-perf] ${key}=${value} 非法；仅允许 0/1/true/false/on/off" >&2
    exit 1
  fi
done

if [[ "$PRINT_EXPORT_FLAGS" -eq 1 ]]; then
  printf '%s\n' \
    "PILOTDECK_EXPORT_SNAPSHOT_V2=$PILOTDECK_EXPORT_SNAPSHOT_V2" \
    "PILOTDECK_UI_DELIVERABLE_CERTIFICATE=$PILOTDECK_UI_DELIVERABLE_CERTIFICATE" \
    "PILOTDECK_UI_EXPORT_SNAPSHOT_V2=$PILOTDECK_UI_EXPORT_SNAPSHOT_V2" \
    "PILOTDECK_UI_EXPORT_USER_AUDIT_MODES=$PILOTDECK_UI_EXPORT_USER_AUDIT_MODES" \
    "PILOTDECK_CAPABILITY_SCOPE_V2=$PILOTDECK_CAPABILITY_SCOPE_V2" \
    "PILOTDECK_QUALITY_CANARY_SLUGS=$PILOTDECK_QUALITY_CANARY_SLUGS" \
    "PILOTDECK_GOAL_QUALITY_CONTRACT=$PILOTDECK_GOAL_QUALITY_CONTRACT" \
    "PILOTDECK_GOAL_QUALITY_CANARY_SLUGS=$PILOTDECK_GOAL_QUALITY_CANARY_SLUGS" \
    "PILOTDECK_GOAL_QUALITY_CANARY_TENANTS=$PILOTDECK_GOAL_QUALITY_CANARY_TENANTS" \
    "PILOTDECK_DELIVERABLE_BRIEF_CONTRACT=$PILOTDECK_DELIVERABLE_BRIEF_CONTRACT" \
    "PILOTDECK_INFER_CAPABILITY_CONTEXT=$PILOTDECK_INFER_CAPABILITY_CONTEXT" \
    "PILOTDECK_SEQUENTIAL_DELIVERABLES=$PILOTDECK_SEQUENTIAL_DELIVERABLES" \
    "PILOTDECK_TRY_PROMPT_CONTRACT_V2=$PILOTDECK_TRY_PROMPT_CONTRACT_V2" \
    "PILOTDECK_OFFICIAL_MEDIA_V2=$PILOTDECK_OFFICIAL_MEDIA_V2" \
    "PILOTDECK_VISUAL_ASSET_PLATFORM=$PILOTDECK_VISUAL_ASSET_PLATFORM" \
    "PILOTDECK_DISCOVER_VISUAL_ASSETS=$PILOTDECK_DISCOVER_VISUAL_ASSETS" \
    "PILOTDECK_VISUAL_ASSET_PREP=$PILOTDECK_VISUAL_ASSET_PREP" \
    "PILOTDECK_AUTO_RESOLVE_VISUAL_ASSETS=$PILOTDECK_AUTO_RESOLVE_VISUAL_ASSETS" \
    "PILOTDECK_VISUAL_BINDING_AUDIT=$PILOTDECK_VISUAL_BINDING_AUDIT" \
    "PILOTDECK_VAP_BIND_BEFORE_WRITE=$PILOTDECK_VAP_BIND_BEFORE_WRITE" \
    "PILOTDECK_VAP_OFFICIAL_FIRST=$PILOTDECK_VAP_OFFICIAL_FIRST" \
    "PILOTDECK_VAP_DISCOVER_PARALLEL=$PILOTDECK_VAP_DISCOVER_PARALLEL" \
    "PILOTDECK_VAP_DIRECT_IMAGE_URL=$PILOTDECK_VAP_DIRECT_IMAGE_URL" \
    "PILOTDECK_VAP_FORCE_LADDER=$PILOTDECK_VAP_FORCE_LADDER" \
    "PILOTDECK_VAP_OUTBOUND_MAX=$PILOTDECK_VAP_OUTBOUND_MAX" \
    "PILOTDECK_VAP_QUERY_PACK=$PILOTDECK_VAP_QUERY_PACK" \
    "PILOTDECK_VAP_CRAWLER_SIDECAR=$PILOTDECK_VAP_CRAWLER_SIDECAR" \
    "PILOTDECK_VAP_LIVE_CAPTURE=$PILOTDECK_VAP_LIVE_CAPTURE" \
    "PILOTDECK_VAP_VISION_LOCATE=$PILOTDECK_VAP_VISION_LOCATE" \
    "PILOTDECK_CONTENT_QUALITY_V2=$PILOTDECK_CONTENT_QUALITY_V2" \
    "PILOTDECK_MARKETING_SITE=$PILOTDECK_MARKETING_SITE" \
    "PILOTDECK_MARKETING_CONTACT=$PILOTDECK_MARKETING_CONTACT" \
    "PILOTDECK_REGISTER_INVITE_CODE=$PILOTDECK_REGISTER_INVITE_CODE" \
    "PILOTDECK_MARKETING_ANALYTICS=$PILOTDECK_MARKETING_ANALYTICS" \
    "PILOTDECK_SHOWCASE_SITE=$PILOTDECK_SHOWCASE_SITE" \
    "PILOTDECK_SHOWCASE_ADMIN=$PILOTDECK_SHOWCASE_ADMIN" \
    "PILOTDECK_MARKETING_I18N=$PILOTDECK_MARKETING_I18N" \
    "PILOTDECK_MARKETING_PAGES_CMS=$PILOTDECK_MARKETING_PAGES_CMS"
  exit 0
fi

if [[ ! -f "$ENV_FILE" ]]; then
  echo "[apply-perf] 找不到 $ENV_FILE，请先完成 Nova 安装" >&2
  exit 1
fi

# 推荐值（仅性能/缓存；不含密钥）
PERF_LINES=(
  'SAAS_CONVERSATION_CATALOG=1'
  'SAAS_CONVERSATION_CATALOG_SHADOW=1'
  'PILOTDECK_HISTORY_SANITIZE=1'
  'PILOTDECK_HISTORY_TAIL_READ=1'
  'PILOTDECK_HISTORY_MESSAGE_CACHE=1'
  'PILOTDECK_SESSION_DELIVERABLE_MANIFEST=1'
  'PILOTDECK_DELIVERABLE_CN_FILENAME_DEFAULT=1'
  'PILOTDECK_COMPLETION_GATE=1'
  'PILOTDECK_VERIFICATION_PASS=1'
  'PILOTDECK_GROUND_TRUTH_RECONCILE=1'
  'PILOTDECK_DELIVERABLE_SUMMARY_FORCE=1'
  'PILOTDECK_REPAIR_CIRCUIT_STRICT=0'
  'PILOTDECK_CHECKLIST_AUTHORITY_TEMPLATES=1'
  'PILOTDECK_SDM_HTML_REPORT_ALIAS=1'
  'PILOTDECK_SDM_GEO_KEYWORD_ALIAS=1'
  'PILOTDECK_SDM_GEO_FAST_CHECK_ALIAS=1'
  'PILOTDECK_RESEARCH_PASSED_GT_STRICT_HTML=1'
  'PILOTDECK_ASSISTANT_COMPLETION_GATE=shadow'
  'PILOTDECK_RESEARCH_DOCX_BASENAME_FUZZY=shadow'
  'PILOTDECK_SDM_HEAL_RESEARCH_LITE=shadow'
  'PILOTDECK_DISTILL_SDM=shadow'
  'PILOTDECK_BLOCK_SILENT_RESEARCH_ADD=shadow'
  'PILOTDECK_OPEN_HTML_MIN_SDM=off'
  'PILOTDECK_BLOCK_DELIVERABLE_SUBAGENT=1'
  'PILOTDECK_OFFICE_EXTENSION_STRICT=shadow'
  'PILOTDECK_PPT_EXPORT_DEFAULT_POLICY=1'
  'PILOTDECK_ORCH_BYPASS_MATRIX_GEO=1'
  'PILOTDECK_MATRIX_CORE_GT_PASS=1'
  'PILOTDECK_PARALLEL_GEO_STAGES=shadow'
  'PILOTDECK_PARALLEL_WRITE_FILE=shadow'
  'PILOTDECK_HTML_FORMAL_ACCEPTANCE=shadow'
  'PILOTDECK_TASK_STAGE_BUDGET=shadow'
  'PILOTDECK_EXPENSIVE_INTENT_CLARIFY=shadow'
  'PILOTDECK_KIND_MENTION_SANITIZE=enforce'
  'PILOTDECK_TOOL_WATCHDOG=1'
  'PILOTDECK_NOVA_SLIDE_IMAGE_PARALLEL=2'
  'PILOTDECK_CN_COMPLIANCE_BINDING=1'
  'VITE_HUB_ENTERPRISE_COMPLIANCE_TAB=shadow'
  'PILOTDECK_HF_STUDIO=1'
  'VITE_PILOTDECK_HF_STUDIO=1'
  'PILOTDECK_PREFLIGHT_STUDIO=off'
  'VITE_PILOTDECK_PREFLIGHT_STUDIO=off'
  # PD-SAAS-FORK: 企业 MCP 首批六键默认 off
  'PILOTDECK_MCP_CN_ERP=off'
  'PILOTDECK_MCP_KINGDEE=off'
  'PILOTDECK_MCP_YONYOU_FIN=off'
  'PILOTDECK_MCP_TAX_INVOICE=off'
  'PILOTDECK_MCP_NOTION=off'
  'PILOTDECK_MCP_POSTGRES=off'
  # PD-SAAS-FORK: IM notify + App chat — production default off (enable explicitly)
  'PILOTDECK_IM_NOTIFY_MCP=off'
  'PILOTDECK_IM_CHANNELS=off'
  'PILOTDECK_PUBLIC_MD_SHARE=shadow'
  'PILOTDECK_OD_TEMPLATE_REGISTRY=shadow'
  'PILOTDECK_BENTO_DECK_EDITOR=0'
  'VITE_BENTO_DECK_PREVIEW=0'
  'PILOTDECK_MD_BROWSER_TOOL=1'
  'VITE_MD_BROWSER_TOOL=1'
  # PD-SAAS-FORK: N2 Bot default off; admin platform-features.json n2Bot or explicit env shadow|enforce enables
  'PILOTDECK_N2_BOT=off'
  'PILOTDECK_PPT_SUPPRESS_FLASK_CONFIRM=1'
  'VITE_PILOTDECK_STICKY_DELIVERABLE_SUMMARY=1'
  'VITE_STICKY_DELIVERABLE_BAR_PERSIST=1'
  'VITE_PILOTDECK_DELIVERABLE_STATUS_LOCK=1'
  # PD-SAAS-FORK: workbench beta 1.1 — production default off (/app unchanged)
  'VITE_WORKBENCH_BETA_11=off'
  'VITE_WORKBENCH_TOUR=off'
  'VITE_TURN_USAGE_FOOTER=off'
  'VITE_POST_DELIVERABLE_NEXT=off'
  'PILOTDECK_UI_WORKBENCH_BETA_11=off'
  'PILOTDECK_VAP_ACQUISITION_CAP=16'
  'PILOTDECK_MEDIA_STRATEGY_RESOLVER=1'
  'PILOTDECK_PREFER_GENERATE_IMAGE=shadow'
  'PILOTDECK_HYPERFRAMES_ENGINE=shadow'
  'PILOTDECK_HYPERFRAMES_HUB_V2=1'
  'PILOTDECK_HYPERFRAMES_MAX_CONCURRENT=1'
  'CACHE_TTL_MESSAGES_SEC=300'
  'CACHE_TTL_CAPABILITIES_SEC=600'
  'CACHE_TTL_PROJECTS_SEC=60'
  'REDIS_URL=redis://redis:6379/0'
  'REDIS_KEY_PREFIX=nova:prod:'
  'PILOTDECK_BACKPRESSURE_MESSAGES=2'
  'PILOTDECK_BACKPRESSURE_VALIDATE=2'
  'PILOTDECK_BACKPRESSURE_PROJECTS=1'
  'PILOTDECK_WEB_PERMISSION_MODE=bypassPermissions'
  'PILOTDECK_GATEWAY_MAX_CONCURRENT_TURNS=7'
  'PILOTDECK_USER_MAX_ACTIVE_TURNS=7'
  'PILOTDECK_USER_MAX_ACTIVE_TURNS_ADMIN=7'
  'PILOTDECK_TURN_QUEUE=1'
  'SAAS_LOGIN_RATE_IP_PER_MIN=10'
  'SAAS_LOGIN_RATE_USER_PER_MIN=30'
  'SAAS_SIDEBAR_DEFAULT_DAYS=7'
  # R2 canary (Train-1): enable after JSONL budget write verified on staging
  'PILOTDECK_TOOL_RESULT_COMPACTION=1'
  # R3 (Train-2): synthetic/repair turn budget — observe 7d before prod-wide
  'PILOTDECK_SESSION_SYNTHETIC_BUDGET=1'
  'PILOTDECK_SESSION_SYNTHETIC_BUDGET_LIMIT=8'
  # PD-SAAS-FORK: 第一阶段默认全关；显式同名 env=1 可灰度，Bridge 运行时覆盖 Vite
  "PILOTDECK_EXPORT_SNAPSHOT_V2=$PILOTDECK_EXPORT_SNAPSHOT_V2"
  "PILOTDECK_UI_EXPORT_SNAPSHOT_V2=$PILOTDECK_UI_EXPORT_SNAPSHOT_V2"
  "PILOTDECK_UI_DELIVERABLE_CERTIFICATE=$PILOTDECK_UI_DELIVERABLE_CERTIFICATE"
  "PILOTDECK_UI_EXPORT_USER_AUDIT_MODES=$PILOTDECK_UI_EXPORT_USER_AUDIT_MODES"
  "PILOTDECK_CAPABILITY_SCOPE_V2=$PILOTDECK_CAPABILITY_SCOPE_V2"
  "PILOTDECK_QUALITY_CANARY_SLUGS=$PILOTDECK_QUALITY_CANARY_SLUGS"
  "PILOTDECK_GOAL_QUALITY_CONTRACT=$PILOTDECK_GOAL_QUALITY_CONTRACT"
  "PILOTDECK_GOAL_QUALITY_CANARY_SLUGS=$PILOTDECK_GOAL_QUALITY_CANARY_SLUGS"
  "PILOTDECK_GOAL_QUALITY_CANARY_TENANTS=$PILOTDECK_GOAL_QUALITY_CANARY_TENANTS"
  "PILOTDECK_DELIVERABLE_BRIEF_CONTRACT=$PILOTDECK_DELIVERABLE_BRIEF_CONTRACT"
  "PILOTDECK_INFER_CAPABILITY_CONTEXT=$PILOTDECK_INFER_CAPABILITY_CONTEXT"
  "PILOTDECK_SEQUENTIAL_DELIVERABLES=$PILOTDECK_SEQUENTIAL_DELIVERABLES"
  "PILOTDECK_TRY_PROMPT_CONTRACT_V2=$PILOTDECK_TRY_PROMPT_CONTRACT_V2"
  "PILOTDECK_OFFICIAL_MEDIA_V2=$PILOTDECK_OFFICIAL_MEDIA_V2"
  "PILOTDECK_VISUAL_ASSET_PLATFORM=$PILOTDECK_VISUAL_ASSET_PLATFORM"
  "PILOTDECK_DISCOVER_VISUAL_ASSETS=$PILOTDECK_DISCOVER_VISUAL_ASSETS"
  "PILOTDECK_VISUAL_ASSET_PREP=$PILOTDECK_VISUAL_ASSET_PREP"
  "PILOTDECK_AUTO_RESOLVE_VISUAL_ASSETS=$PILOTDECK_AUTO_RESOLVE_VISUAL_ASSETS"
  "PILOTDECK_VISUAL_BINDING_AUDIT=$PILOTDECK_VISUAL_BINDING_AUDIT"
  "PILOTDECK_VAP_BIND_BEFORE_WRITE=$PILOTDECK_VAP_BIND_BEFORE_WRITE"
  "PILOTDECK_VAP_OFFICIAL_FIRST=$PILOTDECK_VAP_OFFICIAL_FIRST"
  "PILOTDECK_VAP_DISCOVER_PARALLEL=$PILOTDECK_VAP_DISCOVER_PARALLEL"
  "PILOTDECK_VAP_DIRECT_IMAGE_URL=$PILOTDECK_VAP_DIRECT_IMAGE_URL"
  "PILOTDECK_VAP_FORCE_LADDER=$PILOTDECK_VAP_FORCE_LADDER"
  "PILOTDECK_VAP_OUTBOUND_MAX=$PILOTDECK_VAP_OUTBOUND_MAX"
  "PILOTDECK_VAP_QUERY_PACK=$PILOTDECK_VAP_QUERY_PACK"
  "PILOTDECK_VAP_CRAWLER_SIDECAR=$PILOTDECK_VAP_CRAWLER_SIDECAR"
  "PILOTDECK_VAP_LIVE_CAPTURE=$PILOTDECK_VAP_LIVE_CAPTURE"
  "PILOTDECK_VAP_VISION_LOCATE=$PILOTDECK_VAP_VISION_LOCATE"
  "PILOTDECK_CONTENT_QUALITY_V2=$PILOTDECK_CONTENT_QUALITY_V2"
  "PILOTDECK_MARKETING_SITE=$PILOTDECK_MARKETING_SITE"
  "PILOTDECK_MARKETING_CONTACT=$PILOTDECK_MARKETING_CONTACT"
  "PILOTDECK_REGISTER_INVITE_CODE=$PILOTDECK_REGISTER_INVITE_CODE"
  "PILOTDECK_MARKETING_ANALYTICS=$PILOTDECK_MARKETING_ANALYTICS"
  "PILOTDECK_SHOWCASE_SITE=$PILOTDECK_SHOWCASE_SITE"
  "PILOTDECK_SHOWCASE_ADMIN=$PILOTDECK_SHOWCASE_ADMIN"
  "PILOTDECK_MARKETING_I18N=$PILOTDECK_MARKETING_I18N"
  "PILOTDECK_MARKETING_PAGES_CMS=$PILOTDECK_MARKETING_PAGES_CMS"
)

BACKUP="$ENV_FILE.bak.$(date +%Y%m%d-%H%M%S)"
cp -a "$ENV_FILE" "$BACKUP"
echo "[apply-perf] 已备份 → $BACKUP"

set_or_append() {
  local key="$1"
  local val="$2"
  local line="${key}=${val}"
  if grep -qE "^${key}=" "$ENV_FILE" 2>/dev/null; then
    local old
    old="$(grep -E "^${key}=" "$ENV_FILE" | tail -1 | cut -d= -f2- | tr -d '\r')"
    if [[ "$old" == "$val" ]]; then
      echo "[apply-perf] 保持 ${key}=${val}"
    else
      sed -i "s|^${key}=.*|${line}|" "$ENV_FILE"
      echo "[apply-perf] 更新 ${key}: ${old} → ${val}"
    fi
  else
    echo "$line" >> "$ENV_FILE"
    echo "[apply-perf] 追加 ${line}"
  fi
}

echo "[apply-perf] 合并性能配置到 $ENV_FILE ..."
for entry in "${PERF_LINES[@]}"; do
  key="${entry%%=*}"
  val="${entry#*=}"
  set_or_append "$key" "$val"
done

# 选用 compose 文件
COMPOSE_FILE="docker-compose.prod.yml"
if grep -q '^SAAS_DATABASE_URL=' "$ENV_FILE" 2>/dev/null; then
  if [[ -f "$INSTALL_ROOT/current/docker-compose.prod.pg.yml" ]]; then
    COMPOSE_FILE="docker-compose.prod.pg.yml"
  fi
fi

if [[ "$NO_RESTART" -eq 1 ]]; then
  echo "[apply-perf] --no-restart：已写 .env，请手动 recreate Nova 容器使运行时 flag 生效"
  exit 0
fi

echo "[apply-perf] 重建 nova 容器（使新 .env 生效）..."
cd "$INSTALL_ROOT/current"

# 旧容器若不在当前 compose 项目下，force-recreate 会 Conflict；先删 nova 再 up
if docker ps -a --format '{{.Names}}' | grep -qx 'nova-ai-studio'; then
  docker stop nova-ai-studio 2>/dev/null || true
  docker rm nova-ai-studio 2>/dev/null || true
fi

docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d --no-deps --force-recreate nova

# --no-deps 不会把 nova 加入 redis 所在网络，须手动连接（否则 captcha/API 卡死）
if docker ps --format '{{.Names}}' | grep -qx 'nova-redis'; then
  REDIS_NET="$(docker inspect nova-redis -f '{{range $k,$v := .NetworkSettings.Networks}}{{$k}}{{end}}' | head -1)"
  if [[ -n "$REDIS_NET" ]]; then
    if docker inspect nova-ai-studio -f '{{range $k,$v := .NetworkSettings.Networks}}{{$k}} {{end}}' | grep -qw "$REDIS_NET"; then
      echo "[apply-perf] nova 已在网络 $REDIS_NET"
    else
      docker network connect "$REDIS_NET" nova-ai-studio
      echo "[apply-perf] 已将 nova 接入 redis 网络: $REDIS_NET"
    fi
  fi
fi

echo "[apply-perf] 等待 Bridge 就绪 ..."
sleep 8

if [[ -f "$INSTALL_ROOT/verify-cloud-perf.sh" ]]; then
  echo "[apply-perf] 运行性能校验 ..."
  bash "$INSTALL_ROOT/verify-cloud-perf.sh" "$COMPOSE_FILE" "$ENV_FILE" nova || true
fi

echo "[apply-perf] 完成。本机可跑: PROD_BASE_URL=... DIAG_USER=... npm run test:cloud:chat-load"
