/**
 * Hub「试一下」中文提示词（自动生成，勿手改）
 * Source: scripts/generate-capability-try-prompts.mjs
 * Visible skills: 723
 */
import { hubPromptQualityIssues } from './promptTemplateStrategy.mjs';

/** @type {Record<string, string>} */
export const TRY_PROMPT_ZH = {
  "nova-research-general": "用「Nova-通用调研」围绕【主题】写综合调研报告：背景、发现、舆情与建议。须交付：research-report.md。\n写入系统分配任务目录。",
  "nova-research-user-general": "用「Nova-用户研究」做【产品或人群】的八段式用户研究：画像、场景、痛点与决策因素。须交付：user-research-report.md。\n写入系统分配任务目录。",
  "nova-research-industry-market": "用「Nova-行业市场」写【行业】市场研究报告：规模、产业链、PEST/SWOT 与进入建议。须交付：industry-market-report.md。\n写入系统分配任务目录。",
  "nova-research-product-user": "用「Nova-产品用研」为【产品】写产品用户研究报告，按固定八章展开。须交付：product-user-research.md。\n写入系统分配任务目录。",
  "nova-research-competitor": "用「Nova-竞品对标」对【品类】做竞品全量对标：竞品清单、维度对比与突围策略。须交付：competitor-benchmark-report.md。\n写入系统分配任务目录。",
  "nova-research-academic-professional": "用「Nova-学术专业」写【课题】专业报告：权威信源、严谨结构、参考文献可追溯。须交付：academic-report.md。\n写入系统分配任务目录。",
  "nova-ppt-aesthetic-slides": "用「Nova-美学幻灯」把【主题】做成【页数，如 4】页【画幅，如 16:9】配图 PNG 幻灯：outline → 页描述 → 逐页生图，逐页 slide-NN.png + slide-manifest.json，不要 HTML。须交付：slide-NN.png、slide-manifest.json。\n\n标准成果清单：\n1. slide-NN.png\n2. slide-manifest.json\n写入系统分配任务目录。\n【能力】Nova-Aesthetic Slides（nova-ppt-aesthetic-slides）\n须交付：slide-NN.png、slide-manifest.json。\n【须交付】slide-NN.png、slide-manifest.json\n【目录】写入系统分配任务目录\n【禁】禁 HTML 幻灯替代 PNG 包；禁 generate_image 冒充官图",
  "nova-customer-acquisition-leads": "用「Nova-智能获客」帮我找潜在客户：【行业 + 地区，如：北京的人工智能外包项目】，整理成结构化线索表格报告。须交付：leads-report.md。\n写入系统分配任务目录。",
  "nova-bento-slides": "用「Nova可编辑演示稿」帮我：【说明具体场景、目标与必须包含的信息】。须交付：deck.bento.html。\n写入系统分配任务目录。\n【能力】Nova可编辑演示稿（nova-bento-slides）\n须交付：deck.bento.html。\n【须交付】deck.bento.html\n【目录】写入系统分配任务目录\n【禁】禁静态 HTML 冒充 bento.html；禁 pptx/PNG 包替代终态",
  "geo-competitor-analysis": "用「GEO竞品分析」对比【我的品牌】与【2-3 家竞品】在 AI 搜索中的可见度，输出差距与行动清单。逐模型收录全量矩阵请用 geo-monitor 三件套，本能力不重复矩阵。须交付：geo-competitor-report.md、geo-competitor-report.html、competitor-visibility.md、competitor-visibility.html。\n\n标准成果清单：\n1. geo-competitor-report.md\n2. geo-competitor-report.html\n3. competitor-visibility.md\n4. competitor-visibility.html\n写入系统分配任务目录。\n【能力】AI 竞品可见度（geo-competitor-analysis）\n须交付：geo-competitor-report.md、geo-competitor-report.html、competitor-visibility.md、competitor-visibility.html。\n【须交付】geo-competitor-report.md、geo-competitor-report.html、competitor-visibility.md、competitor-visibility.html\n【目录】写入系统分配任务目录\n【禁】禁非 STDA 目录落盘\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "geo-keyword-research": "用「GEO挖词」为【品牌或产品】整理 AI 搜索关键词（20 个核心词与用户常问句式）。须交付：keywords.md、keywords.html。\n\n标准成果清单：\n1. keywords.md\n2. keywords.html\n写入系统分配任务目录。\n【能力】AI 关键词调研（geo-keyword-research）\n须交付：keywords.md、keywords.html。\n【须交付】keywords.md、keywords.html\n【目录】写入系统分配任务目录\n【禁】禁非 STDA 目录落盘\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "df-consulting-analysis": "用「咨询分析」就【课题】写一份咨询级研究报告：框架化分析与结论建议。",
  "geo-serp-analysis": "用「AI 搜索格局分析」帮我：【说明具体场景、目标与必须包含的信息】。须交付：serp-analysis.md、serp-analysis.html。\n\n标准成果清单：\n1. serp-analysis.md\n2. serp-analysis.html\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "mkt-competitive-intel": "用「竞争情报摘要」汇总【竞品】近 30 天动态，给 3 条应对建议。须交付：intel.md。\n写入系统分配任务目录。",
  "mkt-content-creation": "用「营销内容创作」为【产品或活动】各写一条【渠道，如 LinkedIn 帖 + 小红书文案】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "mkt-draft-content": "用「渠道草稿」按我的内容计划起草本周待发内容：【贴主题或日历】，每个渠道一版。须交付：marketing-deliverable.md。\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "mkt-email-sequence": "用「邮件序列」为【产品】写 5 封新用户邮件：欢迎、价值、案例、催活、转化，各附主题行。须交付：marketing-deliverable.md。\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "mkt-review-mining": "用「评论舆情挖掘」分析这批评论：【粘贴评论或来源链接】，提炼主题、情感与产品痛点。须交付：sentiment-report.md、sentiment-report.html。\n\n标准成果清单：\n1. sentiment-report.md\n2. sentiment-report.html\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "mkt-customer-research": "用「客户调研」整理【产品】的客户洞察：【贴访谈、问卷或评论素材】，输出 ICP 画像与痛点清单。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "df-deep-research": "用「深度调研」围绕【研究主题】做多源调研：先列信息源，再给带结论的综述。须交付：research-report.md。\n写入系统分配任务目录。",
  "df-github-deep-research": "用「GitHub 竞品调研」研究【仓库或开源方向】：项目对比、活跃度与竞争格局。",
  "ala-fact-checker": "用「事实核查」帮我：【说明具体任务与背景】。须交付：output.md 或修订稿（按任务）。\n写入系统分配任务目录。",
  "fc-firecrawl-cli": "用「Firecrawl 联网抓取」帮我：【说明要搜索或抓取的页面/竞品 URL】（需 Firecrawl Key）。",
  "ala-decision-helper": "用「决策助手」帮我：【说明具体任务与背景】。须交付：output.md 或修订稿（按任务）。\n写入系统分配任务目录。",
  "fc-firecrawl-search": "用「Firecrawl 搜索发现」围绕【关键词/主题】搜索并提取来源摘要（需 Firecrawl Key）。",
  "tool-web-search": "用「联网搜索」查【主题】的最新资料，整理 5 条来源与要点。须交付：search-summary.md。\n写入系统分配任务目录。缺 Key 或外部服务不可用时仍交付 md 说明，勿中断。",
  "mcp-firecrawl": "用「网页抓取调研」帮我：【说明要查的数据或要执行的操作】（需已连接对应服务）。",
  "od-research-decision-room": "用「调研决策室」帮我做页面设计：【说明页面类型、内容与风格】。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "mcp-exa": "用「智能联网调研」帮我：【说明要查的数据或要执行的操作】（需已连接对应服务）。",
  "web-just-scrape": "用「轻量网页抓取」抓取【URL】正文并输出 markdown（可能需要 ScrapeGraph Key）。",
  "mcp-similarweb": "用「竞品流量调研」帮我：【说明要查的数据或要执行的操作】（需已连接对应服务）。",
  "ala-editor": "用「专业润色」编辑下面的文稿，提升清晰度与可读性：【粘贴文稿】。须交付：output.md 或修订稿（按任务）。\n写入系统分配任务目录。",
  "ala-meeting-notes": "用「会议纪要」把这份记录整理成结构化纪要：【粘贴录音转写或速记】，列出决策与行动项。须交付：output.md 或修订稿（按任务）。\n写入系统分配任务目录。",
  "ala-technical-writer": "用「技术文档写作」为【项目或功能】写一份【README / 教程 / API 文档】。须交付：output.md 或修订稿（按任务）。\n写入系统分配任务目录。",
  "df-find-skills": "用「技能发现安装」帮我找：【想要的能力，如：自动生成周报】，列出可装的技能并装好。",
  "ala-code-reviewer": "用「代码审查」检查【文件或目录路径】的安全漏洞与质量问题，按严重程度列出并给修复建议。须交付：output.md 或修订稿（按任务）。\n写入系统分配任务目录。",
  "ala-debugger": "用「系统化调试」排查这个问题：【贴报错信息与复现步骤】，定位根因并修复。须交付：output.md 或修订稿（按任务）。\n写入系统分配任务目录。",
  "ala-fullstack-developer": "用「全栈开发」帮我实现：【功能需求，如：给项目加一个带登录的评论功能】。须交付：output.md 或修订稿（按任务）。\n写入系统分配任务目录。",
  "ala-python-expert": "用「Python 专家」帮我：【写脚本 / 优化代码 / 排错，贴需求或代码】。须交付：output.md 或修订稿（按任务）。\n写入系统分配任务目录。",
  "df-bootstrap": "用「AI 伙伴引导」陪我配置专属 AI 助手的性格与风格，一步步问我再生成配置。",
  "df-claude-to-deerflow": "用「DeerFlow 对接」把这个研究任务发给 DeerFlow：【研究主题】（需已部署 DeerFlow）。",
  "df-code-documentation": "用「代码文档生成」为【代码目录或仓库路径】生成 README 与 API 文档。",
  "df-skill-creator": "用「技能创建」帮我做一个新技能：【描述它要做什么】，写好并测试。",
  "df-smoke-test": "用「端到端冒烟测试」对【项目路径或服务地址】跑一轮部署与健康检查，输出测试报告。",
  "df-surprise-me": "用「创意组合展示」围绕【主题】随机组合几个技能，给我一个惊喜成果。",
  "df-vercel-deploy-claimable": "用「部署到 Vercel」把【项目路径】发布上线，给我预览链接。",
  "mkt-pricing": "用「定价包装」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "pd-geo": "用「AI 搜索全案」给【品牌】做完整 AI 可见度包：审计清单、关键词、多平台成稿、optimized.md、评分验证与 HTML 周报。须交付：geo-aeo-audit-checklist.md、geo-aeo-audit-checklist.html、keywords-research.md、keywords-research.html、zhihu-article.md、xiaohongshu-article.md、wechat-article.md、optimized.md、schema.jsonld、citability-report.md、citability-report.html、score-report.md、score-report.html、visibility-report.html。\n\n标准成果清单：\n1. geo-aeo-audit-checklist.md\n2. geo-aeo-audit-checklist.html\n3. keywords-research.md\n4. keywords-research.html\n5. zhihu-article.md\n6. xiaohongshu-article.md\n7. wechat-article.md\n8. optimized.md\n9. schema.jsonld\n10. citability-report.md\n11. citability-report.html\n12. score-report.md\n13. score-report.html\n14. visibility-report.html\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "pms-business-model": "用「business-model」帮我：【说明具体场景、目标与必须包含的信息】。",
  "geo-content-gap-analysis": "用「AI 内容缺口分析」帮我：【说明具体场景、目标与必须包含的信息】。须交付：content-gap.md、content-gap.html。\n\n标准成果清单：\n1. content-gap.md\n2. content-gap.html\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "mkt-revops": "用「B2B 收入运营」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "pms-market-sizing": "用「market-sizing」帮我：【说明具体场景、目标与必须包含的信息】。",
  "pms-metrics-dashboard": "用「metrics-dashboard」帮我：【说明具体场景、目标与必须包含的信息】。",
  "pms-pestle-analysis": "用「pestle-analysis」帮我：【说明具体场景、目标与必须包含的信息】。",
  "pms-cohort-analysis": "用「cohort-analysis」帮我：【说明具体场景、目标与必须包含的信息】。",
  "pms-porters-five-forces": "用「porters-five-forces」帮我：【说明具体场景、目标与必须包含的信息】。",
  "pms-north-star-metric": "用「north-star-metric」帮我：【说明具体场景、目标与必须包含的信息】。",
  "pms-pricing-strategy": "用「pricing-strategy」帮我：【说明具体场景、目标与必须包含的信息】。",
  "pms-competitor-analysis": "用「competitor-analysis」帮我：【说明具体场景、目标与必须包含的信息】。",
  "pms-monetization-strategy": "用「monetization-strategy」帮我：【说明具体场景、目标与必须包含的信息】。",
  "pms-swot-analysis": "用「SWOT 分析」帮我：【说明具体场景、目标与必须包含的信息】。",
  "pms-gtm-strategy": "用「gtm-strategy」帮我：【说明具体场景、目标与必须包含的信息】。",
  "pms-sql-queries": "用「sql-queries」帮我：【说明具体场景、目标与必须包含的信息】。",
  "pms-ansoff-matrix": "用「ansoff-matrix」帮我：【说明具体场景、目标与必须包含的信息】。",
  "pms-gtm-motions": "用「gtm-motions」帮我：【说明具体场景、目标与必须包含的信息】。",
  "mkt-product-marketing": "用「产品营销」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-content-strategy": "用「内容策略」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-marketing-plan": "用「营销计划」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "hub-pack-brand-website": "用「品牌官网全案」帮我：【写出要做的事，如：给新品牌做定位 / 写官网落地页文案 / 规划 SEO 关键词】，并附品牌背景。可做：品牌发现、定位、语气规范、落地页文案、SEO、转化优化、上线清单。须交付：按子任务交付 md/html/docx。\n写入系统分配任务目录。缺 Key 或外部服务不可用时仍交付 md 说明，勿中断。",
  "mkt-marketing-psychology": "用「消费心理」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-marketing-ideas": "用「创意点子」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-launch": "用「上市策略」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-site-architecture": "用「站点结构」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "pms-competitive-battlecard": "用「竞品 Battlecard」帮我：【说明具体场景、目标与必须包含的信息】。须交付：battlecard.md。\n写入系统分配任务目录。",
  "ala-strategy-advisor": "用「strategy-advisor」帮我：【说明具体任务与背景】。",
  "ala-project-planner": "用「项目拆解排期」把这个项目拆成任务与里程碑：【项目目标与期限】。须交付：output.md 或修订稿（按任务）。\n写入系统分配任务目录。",
  "ala-sprint-planner": "用「Sprint 规划」帮团队排下个迭代：【贴需求列表与团队人数】，输出故事点与 Sprint 目标。须交付：output.md 或修订稿（按任务）。\n写入系统分配任务目录。",
  "pilotdeck-skills-migration": "用「技能迁移」把我在【Claude Code 或其他工具】里的技能迁移进来，先扫描再批量导入。",
  "geo-content-optimizer": "用「AI可引用优化」改写下面的内容，让它更容易被 ChatGPT、Perplexity 等引用：【粘贴内容或 URL】。须交付：optimization-report.md、optimization-report.html、optimized.md。\n\n标准成果清单：\n1. optimization-report.md\n2. optimization-report.html\n3. optimized.md\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "social-creative-matrix": "用「社媒矩阵包」把一条创意扩成国内 8 平台图文矩阵：【创意主题】，含 brief、创意锚点、copywriting、manifest 与 visuals/ 四套比例配图（各 generate_image 最多 1 次，禁止 VAP），先不发布。须交付：brief.md、creative-anchors.md、copywriting.md、manifest.json。\n\n标准成果清单：\n1. brief.md\n2. creative-anchors.md\n3. copywriting.md\n4. manifest.json\n写入系统分配任务目录。\n【能力】社媒矩阵包（social-creative-matrix）\n须交付：brief.md、creative-anchors.md、copywriting.md、manifest.json。\n【须交付】brief.md、creative-anchors.md、copywriting.md、manifest.json\n【目录】写入系统分配任务目录\n【禁】禁飞轮幻影三槽扩写",
  "geo-seo-content-writer": "用「AI搜索成稿」写一篇面向 AI 搜索的长文：主题【主题】，目标关键词【关键词】，结构利于 AI 摘录。须交付：content-strategy-report.md、content-strategy-report.html。\n\n标准成果清单：\n1. content-strategy-report.md\n2. content-strategy-report.html\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "geo-citability": "用「AI引用评分」给这个页面打分：【URL 或粘贴内容】，输出可引用性评分与逐段改写建议。须交付：citability-report.md、citability-report.html。\n\n标准成果清单：\n1. citability-report.md\n2. citability-report.html\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "ppt-master": "用「原生可编辑 PPT」帮我：【说明具体场景、目标与必须包含的信息】。须交付：presentation.pptx。\n写入系统分配任务目录。",
  "html-ppt": "用「HTML 幻灯工作室」做 8 页【主题】技术分享 HTML 放映幻灯，主题 cyberpunk-neon，整稿 tech-sharing，按 SKILL 生成可全屏放映的 index.html。须交付：index.html。\n写入系统分配任务目录。",
  "od-digits-fintech": "用「od-digits-fintech」做【主题】的页面或视频分镜：【说明内容与风格】。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "open-design": "用「设计总控」帮我做一个页面：【页面类型与内容，如：产品介绍页，含标题、三个功能、价格和试用按钮】，自动套用合适的设计系统，产出可预览网页。须交付：index.html。\n写入系统分配任务目录。\n【能力】设计总控（open-design）\n须交付：index.html。\n【须交付】index.html\n【目录】写入系统分配任务目录\n【禁】禁非 STDA 目录落盘",
  "anth-docx": "用「Word文档」写一份【文档类型，如活动 brief / 新闻稿】并输出 Word 文件：【主题与要点】。须交付：*.docx。\n写入系统分配任务目录。",
  "mkt-copywriting": "用「广告文案」写【产品】的落地页文案：标题、三个卖点、行动按钮与 FAQ，语气专业简洁。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-copy-editing": "用「文案润色」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-image": "用「营销生图」生成【数量与用途，如 3 张新品宣传图】：【画面内容、风格与尺寸】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-video": "用「营销视频」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-ad-creative": "用「投放创意」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-paywalls": "用「付费墙」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "od-saas-landing": "用「官网落地页」做【产品】介绍页：醒目标题、三个核心功能、价格或试用按钮、页脚联系方式，风格简洁专业。须交付：index.html。\n写入系统分配任务目录。\n【能力】官网落地页（od-saas-landing）\n须交付：index.html。\n【须交付】index.html\n【目录】写入系统分配任务目录\n【禁】禁模板彩虹渐变；禁占位灰块/假按钮；禁 generate_image 冒充官图",
  "od-social-carousel": "用「社媒轮播」做【主题或活动】：【说明必须出现的模块与风格】。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。\n【能力】社媒轮播（od-social-carousel）\n须交付：index.html 或指定页面文件。\n【须交付】index.html 或指定页面文件\n【目录】写入系统分配任务目录\n【禁】禁非 STDA 目录落盘",
  "od-poster-hero": "用「海报主视觉」做【活动】竖版海报：时间地点、三条亮点，底部留二维码位。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-social-x-card": "用「X 分享卡片」做【金句或数据】16:9 分享卡：中央文案、作者署名与类型标签。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "tool-generate-image": "用「对话生图」生成图片：【画面描述 + 数量 + 比例，如 3 张 16:9 露营装备主视觉】。须交付：*.png、*.jpg。\n\n标准成果清单：\n1. *.png\n2. *.jpg\n写入系统分配任务目录。缺 Key 或外部服务不可用时仍交付 md 说明，勿中断。",
  "od-email-marketing": "用「邮件营销页」做【主题或活动】：【说明必须出现的模块与风格】。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "tool-generate-speech": "用「语音合成」：【说明输入内容与期望产出】。须交付：按工具产出对应格式文件。\n写入系统分配任务目录。缺 Key 或外部服务不可用时仍交付 md 说明，勿中断。",
  "od-article-magazine": "用「杂志长文」做【主题或活动】：【说明必须出现的模块与风格】。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-waitlist-page": "用「候补名单页」做【产品】预发布页：品牌名、一句话价值、邮箱收集与提交成功态，风格简洁。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "tool-export-document": "用「一键导出办公文档」：【说明输入内容与期望产出】。须交付：按工具产出对应格式文件。\n写入系统分配任务目录。缺 Key 或外部服务不可用时仍交付 md 说明，勿中断。",
  "tool-transcribe-audio": "用「语音转写」：【说明输入内容与期望产出】。须交付：按工具产出对应格式文件。\n写入系统分配任务目录。缺 Key 或外部服务不可用时仍交付 md 说明，勿中断。",
  "od-deck-magazine": "用「HTML 比稿」做【主题或活动】：【说明必须出现的模块与风格】。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-web-prototype": "用「网页原型页」做【产品或场景】高保真原型：顶栏导航、至少三个内容区块，风格【简约/专业】。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "tool-generate-video": "用「营销生视频」生成一段【时长与用途，如 8 秒抖音开场】视频：【画面描述与节奏】。须交付：*.mp4。\n写入系统分配任务目录。缺 Key 或外部服务不可用时仍交付 md 说明，勿中断。",
  "tool-parse-attachment": "用「分析对话附件」：【说明输入内容与期望产出】。须交付：按工具产出对应格式文件。\n写入系统分配任务目录。缺 Key 或外部服务不可用时仍交付 md 说明，勿中断。",
  "od-mobile-app": "用「手机界面示意」画【2026 FIFA 世界杯观赛指南】，FIFA 蓝金风格，三屏并排、带手机外框。第一步调用 scaffold_mobile_mockup（slug=world-cup-2026，preset=fifa-world-cup），再按需 edit_file 各屏。须交付：screen-*.html。\n写入系统分配任务目录。\n【能力】od-mobile-app（od-mobile-app）\n须交付：screen-*.html。\n【须交付】screen-*.html\n【目录】写入系统分配任务目录\n【禁】禁桌面网页硬塞手机框；禁线框草稿充数",
  "od-team-okrs": "用「团队 OKR 页」做【团队或季度】目标页：三个目标与关键结果进度条、负责人与状态。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "tool-render-html-video": "用「HTML 转视频」把【HTML 页面路径】导出成【时长与分辨率，如 10 秒 1080p】MP4。须交付：*.mp4。\n写入系统分配任务目录。缺 Key 或外部服务不可用时仍交付 md 说明，勿中断。",
  "od-kanban-board": "用「看板任务板」做【项目】看板：待办/进行中/完成三列，每列若干示例卡片。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-mobile-onboarding": "用「新手引导三屏」给【App】做首次打开引导：欢迎、价值说明、开始使用。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-meeting-notes": "用「会议纪要页」整理【会议主题】纪要：议题、决议与行动项（负责人+日期）。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-pricing-page": "用「定价页」做【主题或活动】：【说明必须出现的模块与风格】。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "tool-compose-images-document": "用「图像合成文档」：【说明输入内容与期望产出】。须交付：按工具产出对应格式文件。\n写入系统分配任务目录。缺 Key 或外部服务不可用时仍交付 md 说明，勿中断。",
  "od-docs-page": "用「文档站点页」做【产品】帮助文档页：左侧目录与至少三章正文。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-pricing-upgrade": "用「升级页」做【主题或活动】：【说明必须出现的模块与风格】。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-blog-post": "用「博客文章页」写【主题】长文阅读页：标题、导语与分层正文。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-release-notes-one-pager": "用「更新说明页」做【主题或活动】：【说明必须出现的模块与风格】。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "tool-ocr-editable-pptx": "用「图片转可编辑 PPT」：【说明输入内容与期望产出】。须交付：按工具产出对应格式文件。\n写入系统分配任务目录。缺 Key 或外部服务不可用时仍交付 md 说明，勿中断。",
  "od-data-report": "用「数据报告页」做【主题或活动】：【说明必须出现的模块与风格】。须交付：report.html。\n写入系统分配任务目录。\n【能力】数据报告页（od-data-report）\n须交付：report.html。\n【须交付】report.html\n【目录】写入系统分配任务目录\n【禁】禁非 STDA 目录落盘",
  "od-finance-report": "用「财务报告页」做【业务】经营摘要：四个 KPI 卡片与一张趋势图（示例数据并标注）。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-dashboard": "用「数据看板页」做【业务】管理后台首页：左侧菜单、指标卡片、趋势图，用示例数据。须交付：index.html。\n写入系统分配任务目录。",
  "od-hr-onboarding": "用「入职引导页」做【公司】新人入职页：分步流程、待办清单与对接人。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-faq-page": "用「FAQ 页面」做【主题或活动】：【说明必须出现的模块与风格】。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-pm-spec": "用「产品规格页」写【功能】PRD 展示页：背景、需求列表与验收标准。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-gamified-app": "用「游戏化应用页」做【产品】游戏化界面示意：等级经验条、任务卡与奖励反馈。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-login-flow": "用「登录流程界面」设计【产品】的登录、注册和验证码三个页面，风格简洁。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-deck-swiss": "用「瑞士国际主义 Deck」做【主题】HTML 演示稿：至少四页、16 列网格、单一强调色。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-resume": "用「简历网页」把我的经历做成一页求职页面：【粘贴经历、技能与联系方式】。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "mcp-figma": "用「设计稿协作」帮我：【说明要查的数据或要执行的操作】（需已连接对应服务）。",
  "od-8bit-orbit-video": "用「od-8bit-orbit-video」做【主题】的页面或视频分镜：【说明内容与风格】。",
  "od-after-hours-editorial": "用「深夜编辑风视频」做【主题】的页面或视频分镜：【说明内容与风格】。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-editorial-burgundy": "用「od-editorial-burgundy」做【主题】的页面或视频分镜：【说明内容与风格】。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-field-notes-editorial": "用「田野笔记视频」做【主题】的页面或视频分镜：【说明内容与风格】。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-swiss-creative": "用「od-swiss-creative」做【主题】的页面或视频分镜：【说明内容与风格】。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "od-swiss-user-research-video": "用「od-swiss-user-research-video」做【主题】的页面或视频分镜：【说明内容与风格】。",
  "od-weread-year-in-review-video": "用「od-weread-year-in-review-video」做【主题】的页面或视频分镜：【说明内容与风格】。",
  "df-image-generation": "用「image-generation」帮我：【说明具体场景、目标与必须包含的信息】。",
  "df-video-generation": "用「video-generation」帮我：【说明具体场景、目标与必须包含的信息】。",
  "df-ppt-generation": "用「PPT 生成」做一套演示稿：【主题 + 页数 + 用途，如：10 页融资路演】。",
  "df-frontend-design": "用「前端界面设计」给【产品或页面】做一版高品质界面：【内容与风格偏好】。",
  "frontend-slides": "用「HTML 演示」做【页数】页动画演示：【主题与风格】，横屏翻页、每页一屏。须交付：index.html。\n写入系统分配任务目录。",
  "od-image-gen": "用「生图存档」生成并保存一张【海报 / 封面 / 插画】图片文件：【画面描述与风格】。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。\n【能力】od-image-gen（od-image-gen）\n须交付：index.html 或指定页面文件。\n【须交付】index.html 或指定页面文件\n【目录】写入系统分配任务目录\n【禁】禁非 STDA 目录落盘",
  "df-web-design-guidelines": "用「界面规范审查」对照 Web 设计规范检查【页面代码路径或 URL】，列出不合规项。",
  "od-figma": "用「Figma 工作流」帮我做页面设计：【说明页面类型、内容与风格】。须交付：index.html 或指定页面文件。\n写入系统分配任务目录。",
  "mkt-social": "用「社媒内容与日历」为【产品】排两周内容日历，含 5 条短视频脚本与发布时间。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-emails": "用「邮件序列」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "hub-pack-ad-funnel": "用「广告漏斗全案」帮我：【如：出 10 条广告创意 / 优化落地页转化 / 制定投放预算】，附产品与目标人群。可做：广告创意、漏斗设计、落地页、付费投放、转化优化。须交付：按子任务交付创意/落地页/投放 md。\n写入系统分配任务目录。缺 Key 或外部服务不可用时仍交付 md 说明，勿中断。",
  "mkt-cold-email": "用「冷邮件」写一组 B2B 开发信：目标客户【行业或职位】，产品【产品】，含首封与 2 封跟进。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-community-marketing": "用「社区营销」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-ads": "用「付费投放」帮我：【说明具体场景、目标与必须包含的信息】。须交付：ads-plan.md、channel-matrix.md。\n\n标准成果清单：\n1. ads-plan.md\n2. channel-matrix.md\n写入系统分配任务目录。",
  "mkt-lead-magnets": "用「Lead Magnet」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-sales-enablement": "用「销售赋能」帮我：【说明具体场景、目标与必须包含的信息】。须交付：talk-track.md。\n写入系统分配任务目录。",
  "mkt-co-marketing": "用「联名营销」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-referrals": "用「推荐计划」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-prospecting": "用「潜客开发」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-sms": "用「短信触达」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-onboarding": "用「新用户激活」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-signup": "用「注册转化」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-popups": "用「弹窗转化」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-free-tools": "用「免费工具」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "df-newsletter-generation": "用「Newsletter」帮我：【说明具体场景、目标与必须包含的信息】。",
  "df-podcast-generation": "用「播客内容」把【主题或文章】改成一期播客脚本：开场、对谈要点与结尾。",
  "mkt-seo-audit": "用「SEO 审计」给【网站域名】做全站体检：技术问题、内容缺口与优先修复清单。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-schema": "用「结构化数据」帮我：【说明具体场景、目标与必须包含的信息】。须交付：schema.jsonld。\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "mkt-programmatic-seo": "用「程序化SEO」规划批量落地页：【品类与变量，如「城市 × 服务」】，输出页面模板与生成清单。须交付：programmatic-template.html。\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "yixiaoer": "用「国内社媒发布」把这篇图文存到【平台，如小红书】草稿箱：【粘贴内容或文件】，先不公开发布。须交付：draft-task-id.txt。\n写入系统分配任务目录。",
  "hub-pack-aso": "用「应用商店优化」帮我：【如：挖关键词 / 改商店标题与描述 / 审计竞品 ASO】，附应用名称与商店链接。可做：关键词、元数据、截图方案、竞品分析、评论分析、Apple 搜索广告。须交付：关键词与元数据优化 md。\n写入系统分配任务目录。缺 Key 或外部服务不可用时仍交付 md 说明，勿中断。",
  "mcp-postiz": "用「海外社媒发布」帮我：【说明要查的数据或要执行的操作】（需已连接对应服务）。",
  "mkt-directory-submissions": "用「目录提交」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-ai-seo": "用「AI 可见度快检」给【品牌或官网】做一轮 AI 搜索可见度快检，列出优先改进项。须交付：audit-checklist.md、audit-checklist.html、competitor-visibility.md、competitor-visibility.html。\n\n标准成果清单：\n1. audit-checklist.md\n2. audit-checklist.html\n3. competitor-visibility.md\n4. competitor-visibility.html\n写入系统分配任务目录。",
  "geo-aeo-audit": "用「AI可见审计」对【官网 URL】做四维 GEO 评分，输出修复清单与优先级。须交付：geo-aeo-audit-checklist.md、geo-aeo-audit-checklist.html。\n\n标准成果清单：\n1. geo-aeo-audit-checklist.md\n2. geo-aeo-audit-checklist.html\n写入系统分配任务目录。",
  "geo-technical-seo": "用「AI爬虫可达」检查【官网 URL】的技术 SEO：robots、llms.txt、结构化数据与可抓取性，输出修复清单。须交付：technical-seo-audit.md、technical-seo-audit.html。\n\n标准成果清单：\n1. technical-seo-audit.md\n2. technical-seo-audit.html\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "geo-on-page-audit": "用「页面可见审计」审计【页面 URL】：标题、结构、关键词与内链，列出优先修复项。须交付：on-page-audit.md、on-page-audit.html。\n\n标准成果清单：\n1. on-page-audit.md\n2. on-page-audit.html\n写入系统分配任务目录。",
  "geo-cn-crawlers": "用「国内 AI 爬虫可达」检查【官网】对通义/豆包/文心等爬虫的可达性与 llms.txt，输出修复建议（技术层，不含逐模型收录矩阵）。须交付：aeo-audit.md、aeo-audit.html、llms.txt。\n\n标准成果清单：\n1. aeo-audit.md\n2. aeo-audit.html\n3. llms.txt\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "geo-visibility-probe": "用「大模型收录探测」对【品牌/产品/事件】做十一模型收录分析：国内必测豆包、DeepSeek、千问、百度、Kimi、腾讯元宝；国外必测 OpenAI、Gemini、Claude、Grok、Meta AI。8–12 条问句，输出 llm_coverage（11 行 models + gaps + optimization）。缺 Key 须 skipped 占位。完整报告由 geo-monitor-report 产出。须交付：monitor-data.json、probe-results.json。\n\n标准成果清单：\n1. monitor-data.json\n2. probe-results.json\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "geo-monitor-hub": "用「GEO 监测编排」为【品牌/产品/事件】聚合监测：先完成十一模型收录探测并写入 llm_coverage（必含全部 11 个 id），再合并 AgentAEO（可选），产出 monitor-data.json。勿重复全量探测。须交付：monitor-data.json。\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "geo-rank-track": "用「AI可见跟踪」给【品牌】建 AI 可见度跟踪表：本月基线与监测关键词。须交付：rank-track.md、rank-track.html。\n\n标准成果清单：\n1. rank-track.md\n2. rank-track.html\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "geo-monitor-report": "用「GEO 监测报告」读取 monitor-data.json，生成 monitor-report.md + geo-monitor-report.html，须含主流大模型收录分析、缺口与 P0/P1 优化建议。须交付：monitor-report.md、geo-monitor-report.html、monitor-data.json。\n\n标准成果清单：\n1. monitor-report.md\n2. geo-monitor-report.html\n3. monitor-data.json\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "geo-dual-report": "用「GEO 报告 HTML 同步」帮我：【说明具体场景、目标与必须包含的信息】。须交付：（内部）将分析 MD 同步为同名 HTML。\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "df-data-analysis": "用「深度分析」帮我：【说明具体场景、目标与必须包含的信息】。",
  "df-chart-visualization": "用「图表可视化」帮我：【说明具体场景、目标与必须包含的信息】。",
  "geo-performance-reporter": "用「AI 可见度绩效报告」帮我：【说明具体场景、目标与必须包含的信息】。须交付：performance-report.md、performance-report.html。\n\n标准成果清单：\n1. performance-report.md\n2. performance-report.html\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "mkt-performance-report": "用「投放效果报告」把【渠道数据】整理成一页效果报告：核心指标、趋势与建议。须交付：performance-summary.md、performance-summary.html。\n\n标准成果清单：\n1. performance-summary.md\n2. performance-summary.html\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "mkt-churn-prevention": "用「流失预防」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "geo-backlink-analyzer": "用「外链与引用分析」帮我：【说明具体场景、目标与必须包含的信息】。须交付：backlink-report.md、backlink-report.html。\n\n标准成果清单：\n1. backlink-report.md\n2. backlink-report.html\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "mkt-cro": "用「转化率优化」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-analytics": "用「数据分析」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mcp-ads": "用「投放数据」帮我：【说明要查的数据或要执行的操作】（需已连接对应服务）。",
  "mkt-ab-testing": "用「A/B 测试」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mcp-seo-data": "用「SEO 数据」帮我：【说明要查的数据或要执行的操作】（需已连接对应服务）。",
  "mcp-creatorcrawl": "用「社媒数据」帮我：【说明要查的数据或要执行的操作】（需已连接对应服务）。",
  "teacher-biology-homework-generation": "用「teacher-biology-homework-generation」出一份分层作业：【年级 + 本周所学内容】，含基础、提高两档，附答案。须交付：homework.md。\n写入系统分配任务目录。",
  "teacher-biology-lesson-planning": "用「teacher-biology-lesson-planning」帮我设计一节课：【年级 + 课题，如：八年级上册《光的折射》】，输出教学目标、课堂活动、提问设计与配套练习。须交付：lesson-plan.md。\n写入系统分配任务目录。",
  "teacher-biology-unit-review": "用「teacher-biology-unit-review」帮我复习：【年级 + 单元名】，输出知识结构图、易错点清单和一套自测题。须交付：unit-review.md。\n写入系统分配任务目录。",
  "teacher-chemistry-homework-generation": "用「teacher-chemistry-homework-generation」出一份分层作业：【年级 + 本周所学内容】，含基础、提高两档，附答案。须交付：homework.md。\n写入系统分配任务目录。",
  "teacher-chemistry-lesson-planning": "用「teacher-chemistry-lesson-planning」帮我设计一节课：【年级 + 课题，如：八年级上册《光的折射》】，输出教学目标、课堂活动、提问设计与配套练习。须交付：lesson-plan.md。\n写入系统分配任务目录。",
  "anth-pdf": "用「PDF工具」处理这份 PDF：【提取正文 / 合并 / 整理成笔记，附文件】。须交付：办公格式文件（docx/pptx/xlsx/pdf）。\n写入系统分配任务目录。",
  "edu-fun-caveman": "用「趣味 CLI 学习」以轻松方式解释【概念】（非课纲，偏趣味探索）。",
  "teacher-chemistry-unit-review": "用「teacher-chemistry-unit-review」帮我复习：【年级 + 单元名】，输出知识结构图、易错点清单和一套自测题。须交付：unit-review.md。\n写入系统分配任务目录。",
  "teacher-chinese-homework-generation": "用「teacher-chinese-homework-generation」出一份分层作业：【年级 + 本周所学内容】，含基础、提高两档，附答案。须交付：homework.md。\n写入系统分配任务目录。",
  "teacher-chinese-lesson-planning": "用「teacher-chinese-lesson-planning」帮我设计一节课：【年级 + 课题，如：八年级上册《光的折射》】，输出教学目标、课堂活动、提问设计与配套练习。须交付：lesson-plan.md。\n写入系统分配任务目录。",
  "ora-brainstorm-research": "用「研究选题脑暴」围绕【研究方向】收敛选题：给 3 个可验证假设与实验设计草图。须交付：academic-output.md 或论文级图表 PDF/SVG。\n写入系统分配任务目录。",
  "teacher-chinese-unit-review": "用「teacher-chinese-unit-review」帮我复习：【年级 + 单元名】，输出知识结构图、易错点清单和一套自测题。须交付：unit-review.md。\n写入系统分配任务目录。",
  "teacher-class-analysis-lite": "用「班级学情分析」分析班级情况：【贴成绩、错题或课堂观察记录】，给出能立刻调整教学的判断。",
  "ora-research-manager": "用「研究项目管理」整理【课题】的文献、实验与笔记：输出研究日志与下周计划。须交付：academic-output.md 或论文级图表 PDF/SVG。\n写入系统分配任务目录。",
  "teacher-english-homework-generation": "用「teacher-english-homework-generation」出一份分层作业：【年级 + 本周所学内容】，含基础、提高两档，附答案。须交付：homework.md。\n写入系统分配任务目录。",
  "teacher-english-lesson-planning": "用「teacher-english-lesson-planning」帮我设计一节课：【年级 + 课题，如：八年级上册《光的折射》】，输出教学目标、课堂活动、提问设计与配套练习。须交付：lesson-plan.md。\n写入系统分配任务目录。",
  "ora-rigor-reviewer": "用「论文严谨性评审」评审这篇稿子：【附论文或草稿】，按审稿标准给分项评分与修改清单。须交付：academic-output.md 或论文级图表 PDF/SVG。\n写入系统分配任务目录。",
  "teacher-english-unit-review": "用「teacher-english-unit-review」帮我复习：【年级 + 单元名】，输出知识结构图、易错点清单和一套自测题。须交付：unit-review.md。\n写入系统分配任务目录。",
  "teacher-geography-homework-generation": "用「teacher-geography-homework-generation」出一份分层作业：【年级 + 本周所学内容】，含基础、提高两档，附答案。须交付：homework.md。\n写入系统分配任务目录。",
  "teacher-geography-lesson-planning": "用「teacher-geography-lesson-planning」帮我设计一节课：【年级 + 课题，如：八年级上册《光的折射》】，输出教学目标、课堂活动、提问设计与配套练习。须交付：lesson-plan.md。\n写入系统分配任务目录。",
  "df-academic-paper-review": "用「学术论文评审」评阅这篇论文：【附文件】，分析方法、贡献与改进建议。",
  "teacher-geography-unit-review": "用「teacher-geography-unit-review」帮我复习：【年级 + 单元名】，输出知识结构图、易错点清单和一套自测题。须交付：unit-review.md。\n写入系统分配任务目录。",
  "teacher-history-homework-generation": "用「teacher-history-homework-generation」出一份分层作业：【年级 + 本周所学内容】，含基础、提高两档，附答案。须交付：homework.md。\n写入系统分配任务目录。",
  "teacher-history-lesson-planning": "用「teacher-history-lesson-planning」帮我设计一节课：【年级 + 课题，如：八年级上册《光的折射》】，输出教学目标、课堂活动、提问设计与配套练习。须交付：lesson-plan.md。\n写入系统分配任务目录。",
  "ora-ml-paper-writing": "用「ML 论文撰写」辅导我这篇作文：【贴题目与我的草稿（没写也行）】，从审题立意到结构语言一步步改。须交付：academic-output.md 或论文级图表 PDF/SVG。\n写入系统分配任务目录。",
  "teacher-history-unit-review": "用「teacher-history-unit-review」帮我复习：【年级 + 单元名】，输出知识结构图、易错点清单和一套自测题。须交付：unit-review.md。\n写入系统分配任务目录。",
  "teacher-homework-generation": "用「作业生成」出一份分层作业：【年级 + 本周所学内容】，含基础、提高两档，附答案。须交付：homework.md。\n写入系统分配任务目录。",
  "df-systematic-literature-review": "用「系统文献综述」围绕【主题】做文献综述：检索、筛选、主题归纳与参考文献表。",
  "teacher-lesson-planning": "用「老师备课」帮我设计一节课：【年级 + 课题】，输出教学目标、课堂活动、提问设计与配套练习。须交付：lesson-plan.md。\n写入系统分配任务目录。",
  "teacher-math-homework-generation": "用「teacher-math-homework-generation」出一份分层作业：【年级 + 本周所学内容】，含基础、提高两档，附答案。须交付：homework.md。\n写入系统分配任务目录。",
  "ora-systems-paper-writing": "用「系统论文撰写」辅导我这篇作文：【贴题目与我的草稿（没写也行）】，从审题立意到结构语言一步步改。须交付：academic-output.md 或论文级图表 PDF/SVG。\n写入系统分配任务目录。",
  "teacher-math-lesson-planning": "用「teacher-math-lesson-planning」帮我设计一节课：【年级 + 课题，如：八年级上册《光的折射》】，输出教学目标、课堂活动、提问设计与配套练习。须交付：lesson-plan.md。\n写入系统分配任务目录。",
  "teacher-math-unit-review": "用「teacher-math-unit-review」帮我复习：【年级 + 单元名】，输出知识结构图、易错点清单和一套自测题。须交付：unit-review.md。\n写入系统分配任务目录。",
  "teacher-parent-report-lite": "用「家长反馈报告」把学生表现写成家长反馈：【贴学生情况】，客观、易懂、不制造焦虑。",
  "ora-academic-plotting": "用「学术图表绘制」把【实验数据】画成论文级图表：折线与消融对比，输出 PDF/SVG。须交付：academic-output.md 或论文级图表 PDF/SVG。\n写入系统分配任务目录。",
  "teacher-physics-homework-generation": "用「teacher-physics-homework-generation」出一份分层作业：【年级 + 本周所学内容】，含基础、提高两档，附答案。须交付：homework.md。\n写入系统分配任务目录。",
  "teacher-physics-lesson-planning": "用「teacher-physics-lesson-planning」帮我设计一节课：【年级 + 课题，如：八年级上册《光的折射》】，输出教学目标、课堂活动、提问设计与配套练习。须交付：lesson-plan.md。\n写入系统分配任务目录。",
  "teacher-physics-unit-review": "用「teacher-physics-unit-review」帮我复习：【年级 + 单元名】，输出知识结构图、易错点清单和一套自测题。须交付：unit-review.md。\n写入系统分配任务目录。",
  "teacher-politics-homework-generation": "用「teacher-politics-homework-generation」出一份分层作业：【年级 + 本周所学内容】，含基础、提高两档，附答案。须交付：homework.md。\n写入系统分配任务目录。",
  "teacher-politics-lesson-planning": "用「teacher-politics-lesson-planning」帮我设计一节课：【年级 + 课题，如：八年级上册《光的折射》】，输出教学目标、课堂活动、提问设计与配套练习。须交付：lesson-plan.md。\n写入系统分配任务目录。",
  "teacher-politics-unit-review": "用「teacher-politics-unit-review」帮我复习：【年级 + 单元名】，输出知识结构图、易错点清单和一套自测题。须交付：unit-review.md。\n写入系统分配任务目录。",
  "college-academic-writing": "用「大学学术写作」改这段写作：【粘贴段落与课程要求】，理清论点与证据，规范引用。",
  "ala-academic-researcher": "用「学术写作助手」帮我：【文献综述 / 论文分析 / 写作润色，附材料与要求】。须交付：output.md 或修订稿（按任务）。\n写入系统分配任务目录。",
  "adult-language-learning": "用「adult-language-learning」帮我：【说明具体场景、目标与必须包含的信息】。",
  "college-cs-data-structure": "用「数据结构」教我【主题，如二叉树】：图示讲解、手写过程，再出一道练习。",
  "college-ai-foundation": "用「AI 基础」带我入门【主题，如大模型原理】：概念地图加一个能跑的小实验。",
  "college-cs-algorithm-interview": "用「算法面试」陪我练一道【题型，如动态规划】：先让我说思路，再纠正并复盘。",
  "college-cs-python": "用「Python 学习」教我【主题】：讲解加小练习，今天完成一个能运行的小成果。",
  "college-data-analysis": "用「学业·数据分析」完成课程数据分析：【贴数据与作业要求】，从清洗到结论与图表。",
  "agent-study-plan": "用「学习计划」帮我排学习计划：【年级 + 目标 + 每天可用时间】，拆到本周每天。",
  "agent-focus-training": "用「专注力训练」给孩子做专注训练方案：【年级 + 具体表现，如写作业坐不住】。",
  "agent-holiday-plan": "用「寒暑假提升」排假期计划：【年级 + 假期时长 + 想提升的科目】，学习与休息平衡。",
  "agent-homework-companion": "用「作业陪伴」陪孩子写今天的作业：【年级 + 作业内容】，卡住时给提示但不代写。",
  "agent-learning-habit": "用「学习习惯」帮孩子养成【习惯，如每天预习 15 分钟】：给固定触发动作与打卡表。",
  "agent-learning-report": "用「学情报告」把这些记录整理成学情报告：【贴练习与考试记录】，家长老师都能看懂。",
  "agent-memory-method": "用「记忆方法」帮我背【内容，如英语单词、古文】：设计可提取、可复习的记忆任务。",
  "agent-mistake-review": "用「错题复盘」分析这些错题：【贴错题】，找出错误模式并排追练计划。",
  "agent-photo-question": "用「拍照答疑」讲这道题：【拍照上传】，先讲思路再确认我听懂。",
  "agent-preview-assistant": "用「课前预习」帮我预习：【年级 + 明天要学的内容】，扫要点、标疑问、列课堂关注点。",
  "agent-review-assistant": "用「复习助手」带我复习【科目 + 范围】：先自测检索，再补漏与归纳。",
  "agent-socratic-tutor": "用「启发式讲解」教我【概念或题目】：用提问引导我自己想到答案。",
  "agent-weakness-boost": "用「薄弱项提升」攻克【薄弱点，如二次函数】：诊断、专项练习与复测。",
  "agent-weekly-review": "用「每周复盘」复盘这周学习：【贴本周情况】，输出进步、问题与下周行动。",
  "agent-question-explanation": "用「AI 讲题」讲这道题：【贴题目 + 年级】，用我能听懂的方式拆解，最后出一道变式题确认。",
  "junior-biology-bs-textbook-sync": "用「junior-biology-bs-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "junior-biology-rj-textbook-sync": "用「junior-biology-rj-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "junior-chemistry-lk-textbook-sync": "用「junior-chemistry-lk-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "junior-chemistry-rj-textbook-sync": "用「junior-chemistry-rj-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "junior-chinese-tongbian-textbook-sync": "用「junior-chinese-tongbian-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "junior-english-rj-textbook-sync": "用「junior-english-rj-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "junior-english-wy-textbook-sync": "用「junior-english-wy-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "junior-english-yl-textbook-sync": "用「junior-english-yl-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "junior-geography-rj-textbook-sync": "用「junior-geography-rj-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "junior-geography-xj-textbook-sync": "用「junior-geography-xj-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "junior-history-tongbian-textbook-sync": "用「junior-history-tongbian-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "junior-math-bs-textbook-sync": "用「junior-math-bs-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "junior-math-rj-textbook-sync": "用「junior-math-rj-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "junior-math-sj-textbook-sync": "用「junior-math-sj-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "junior-physics-lk-textbook-sync": "用「junior-physics-lk-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "junior-physics-rj-textbook-sync": "用「junior-physics-rj-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "junior-politics-tongbian-textbook-sync": "用「junior-politics-tongbian-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "primary-chinese-tongbian-textbook-sync": "用「primary-chinese-tongbian-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "primary-english-pep-textbook-sync": "用「primary-english-pep-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "primary-english-wy-textbook-sync": "用「primary-english-wy-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "primary-english-yl-textbook-sync": "用「primary-english-yl-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "primary-math-bs-textbook-sync": "用「primary-math-bs-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "primary-math-rj-textbook-sync": "用「primary-math-rj-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "primary-math-sj-textbook-sync": "用「primary-math-sj-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "senior-biology-bs-textbook-sync": "用「senior-biology-bs-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "senior-biology-rj-textbook-sync": "用「senior-biology-rj-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "senior-chemistry-lk-textbook-sync": "用「senior-chemistry-lk-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "senior-chemistry-rj-textbook-sync": "用「senior-chemistry-rj-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "senior-chinese-tongbian-textbook-sync": "用「senior-chinese-tongbian-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "senior-english-rj-textbook-sync": "用「senior-english-rj-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "senior-english-wy-textbook-sync": "用「senior-english-wy-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "senior-geography-rj-textbook-sync": "用「senior-geography-rj-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "senior-geography-xj-textbook-sync": "用「senior-geography-xj-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "senior-history-tongbian-textbook-sync": "用「senior-history-tongbian-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "senior-math-bs-textbook-sync": "用「senior-math-bs-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "senior-math-rja-textbook-sync": "用「senior-math-rja-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "senior-math-rjb-textbook-sync": "用「senior-math-rjb-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "senior-physics-lk-textbook-sync": "用「senior-physics-lk-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "senior-physics-rj-textbook-sync": "用「senior-physics-rj-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "senior-politics-tongbian-textbook-sync": "用「senior-politics-tongbian-textbook-sync」陪我学：【年级册别 + 单元或课文】，先讲要点再出同步练习，错了帮我订正。",
  "adult-vocational-certificate": "用「adult-vocational-certificate」帮我备考：【考试时间与目前水平】，先诊断再给每日限时训练计划。",
  "civil-service-aptitude": "用「civil-service-aptitude」帮我备考：【考试时间与目前水平】，先诊断再给每日限时训练计划。",
  "civil-service-essay": "用「公务员申论」陪我练申论：【贴题目或材料】，先写提纲，再逐段点评。",
  "teacher-certification-sprint": "用「teacher-certification-sprint」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "college-cet4-sprint": "用「college-cet4-sprint」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "college-cet6-sprint": "用「college-cet6-sprint」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "ielts-prep": "用「ielts-prep」帮我备考：【目标分数与考试时间】，听说读写诊断后给分项训练。",
  "postgraduate-english-sprint": "用「postgraduate-english-sprint」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "toefl-prep": "用「toefl-prep」帮我备考：【目标分数与考试时间】，听说读写诊断后给分项训练。",
  "junior-biology-exam-review": "用「junior-biology-exam-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "junior-chemistry-exam-review": "用「junior-chemistry-exam-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "junior-chinese-exam-review": "用「junior-chinese-exam-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "junior-english-exam-review": "用「junior-english-exam-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "junior-geography-exam-review": "用「junior-geography-exam-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "junior-history-exam-review": "用「junior-history-exam-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "junior-math-exam-review": "用「junior-math-exam-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "junior-physics-exam-review": "用「junior-physics-exam-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "junior-politics-exam-review": "用「junior-politics-exam-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "junior-zhongkao-sprint": "用「junior-zhongkao-sprint」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "primary-final-review": "用「primary-final-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "senior-biology-exam-review": "用「senior-biology-exam-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "senior-chemistry-exam-review": "用「senior-chemistry-exam-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "senior-chinese-exam-review": "用「senior-chinese-exam-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "senior-english-exam-review": "用「senior-english-exam-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "senior-gaokao-sprint": "用「senior-gaokao-sprint」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "senior-geography-exam-review": "用「senior-geography-exam-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "senior-history-exam-review": "用「senior-history-exam-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "senior-math-exam-review": "用「senior-math-exam-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "senior-physics-exam-review": "用「senior-physics-exam-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "senior-politics-exam-review": "用「senior-politics-exam-review」帮我备考：【年级 + 考试时间 + 薄弱章节】，先诊断再给两周复习计划。",
  "junior-biology-quick-practice": "用「junior-biology-quick-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "junior-chemistry-quick-practice": "用「junior-chemistry-quick-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "junior-chinese-quick-practice": "用「junior-chinese-quick-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "junior-english-quick-practice": "用「junior-english-quick-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "junior-english-vocabulary-daily": "用「junior-english-vocabulary-daily」出今天 10 分钟词汇练习：【年级 + 词表或单元】，做完批改。",
  "junior-geography-quick-practice": "用「junior-geography-quick-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "junior-history-quick-practice": "用「junior-history-quick-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "junior-math-daily-practice": "用「junior-math-daily-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "junior-math-quick-practice": "用「junior-math-quick-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "junior-physics-quick-practice": "用「junior-physics-quick-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "junior-politics-quick-practice": "用「junior-politics-quick-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "primary-chinese-dictation-daily": "用「primary-chinese-dictation-daily」出今天的听写练习：【年级 + 本周生字词】，做完帮我批改。",
  "primary-chinese-recitation-daily": "用「primary-chinese-recitation-daily」帮我背：【课文或古诗名】，分段检查能否完整复述。",
  "primary-english-vocabulary-daily": "用「primary-english-vocabulary-daily」出今天 10 分钟词汇练习：【年级 + 词表或单元】，做完批改。",
  "primary-math-mental-arithmetic": "用「primary-math-mental-arithmetic」出今天 10 分钟口算：【年级 + 运算类型】，做完批改并讲错题。",
  "primary-reading-daily": "用「primary-reading-daily」出一篇阅读短练：【年级 + 文章或主题】，练读懂、找依据、组织答案。",
  "senior-biology-quick-practice": "用「senior-biology-quick-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "senior-chemistry-quick-practice": "用「senior-chemistry-quick-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "senior-chinese-quick-practice": "用「senior-chinese-quick-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "senior-english-quick-practice": "用「senior-english-quick-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "senior-english-vocabulary-daily": "用「senior-english-vocabulary-daily」出今天 10 分钟词汇练习：【年级 + 词表或单元】，做完批改。",
  "senior-geography-quick-practice": "用「senior-geography-quick-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "senior-history-quick-practice": "用「senior-history-quick-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "senior-math-quick-practice": "用「senior-math-quick-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "senior-physics-quick-practice": "用「senior-physics-quick-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "senior-politics-quick-practice": "用「senior-politics-quick-practice」出今天的 10 分钟练习：【年级 + 最近所学】，做完帮我批改并讲错题。",
  "adult-workplace-writing": "用「adult-workplace-writing」辅导我这篇作文：【贴题目与我的草稿（没写也行）】，从审题立意到结构语言一步步改。",
  "junior-chinese-composition": "用「junior-chinese-composition」辅导我这篇作文：【贴题目与我的草稿（没写也行）】，从审题立意到结构语言一步步改。",
  "junior-chinese-modern-reading": "用「junior-chinese-modern-reading」练这篇阅读：【贴文章与题目】，教我找依据、组织答案。",
  "junior-english-writing": "用「junior-english-writing」辅导这篇英语作文：【贴题目与草稿】，从任务回应、结构到句子逐层改。",
  "primary-chinese-reading": "用「primary-chinese-reading」练这篇阅读：【贴文章与题目】，教我找依据、组织答案。",
  "primary-chinese-writing": "用「primary-chinese-writing」辅导我这篇作文：【贴题目与我的草稿（没写也行）】，从审题立意到结构语言一步步改。",
  "primary-english-reading": "用「primary-english-reading」练这篇阅读：【贴文章与题目】，教我找依据、组织答案。",
  "senior-chinese-essay": "用「senior-chinese-essay」辅导我这篇作文：【贴题目与我的草稿（没写也行）】，从审题立意到结构语言一步步改。",
  "senior-chinese-reading": "用「senior-chinese-reading」练这篇阅读：【贴文章与题目】，教我找依据、组织答案。",
  "senior-english-writing": "用「senior-english-writing」辅导这篇英语作文：【贴题目与草稿】，从任务回应、结构到句子逐层改。",
  "agent-parent-companion": "用「家长陪学」给我一套陪学脚本：【孩子年级 + 困扰场景】，少催促、可执行。",
  "family-emotion-support": "用「family-emotion-support」帮我处理：【具体家庭学习场景与现状】，给可执行方案。",
  "family-holiday-learning": "用「family-holiday-learning」帮我处理：【具体家庭学习场景与现状】，给可执行方案。",
  "family-homework-routine": "用「family-homework-routine」帮我处理：【具体家庭学习场景与现状】，给可执行方案。",
  "family-reading-companion": "用「family-reading-companion」帮我处理：【具体家庭学习场景与现状】，给可执行方案。",
  "family-school-communication": "用「family-school-communication」帮我处理：【具体家庭学习场景与现状】，给可执行方案。",
  "family-screen-time-balance": "用「family-screen-time-balance」帮我处理：【具体家庭学习场景与现状】，给可执行方案。",
  "preschool-attention-training": "用「preschool-attention-training」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "preschool-classroom-rules": "用「preschool-classroom-rules」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "preschool-color-shape": "用「preschool-color-shape」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "preschool-emotion-expression": "用「preschool-emotion-expression」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "preschool-family-readiness": "用「preschool-family-readiness」给孩子做幼小衔接准备计划：【孩子年龄与入学时间】。",
  "preschool-fine-motor-writing": "用「preschool-fine-motor-writing」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "preschool-growth-report": "用「学前成长观察报告」把这段时间的观察记录整理成成长报告：【贴观察记录】。",
  "preschool-language-expression": "用「preschool-language-expression」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "preschool-life-habits": "用「preschool-life-habits」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "preschool-literacy-foundation": "用「preschool-literacy-foundation」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "preschool-logic-thinking": "用「preschool-logic-thinking」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "preschool-memory-observation": "用「preschool-memory-observation」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "preschool-number-sense-foundation": "用「preschool-number-sense-foundation」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "preschool-parent-daily-play": "用「preschool-parent-daily-play」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "preschool-picture-book-reading": "用「preschool-picture-book-reading」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "preschool-pinyin-foundation": "用「preschool-pinyin-foundation」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "preschool-school-readiness": "用「preschool-school-readiness」给孩子做幼小衔接准备计划：【孩子年龄与入学时间】。",
  "preschool-self-care": "用「preschool-self-care」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "preschool-shape-space": "用「preschool-shape-space」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "preschool-social-skills": "用「preschool-social-skills」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "preschool-story-retelling": "用「preschool-story-retelling」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "preschool-task-awareness": "用「preschool-task-awareness」给孩子安排今天的小任务：【孩子年龄 + 当前情况】，要好玩、家长能照着做。",
  "legal-risk-assessment": "用「法务风险评估」评估【合同/条款摘要】风险分级；注明非律师意见，须法务复核。须交付：risk-assessment.md。\n写入系统分配任务目录。",
  "legal-response": "用「法律回应草稿」起草对【函件/投诉】的初步回应；注明非律师意见，须法务复核。须交付：response-draft.md。\n写入系统分配任务目录。",
  "mcp-google-workspace": "用「Google 办公套件」帮我：【读或写哪个文档、表格、日历，说明内容】（需已连接 Google 账号）。",
  "mcp-notion-collab": "用「Notion 协作」把内容写入或读出我的 Notion。\n\n【你在做什么】在已授权的 Notion 工作区读写页面或数据库行。\n\n【请填写】（不知道就写「不清楚」，不要空着）\n- 动作：【读取 / 新建页 / 更新数据库行】\n- 页面或数据库名称：【】\n- 要写入的要点：【】\n\n【请准备】需管理员启用 Notion 协作并配置 Integration Token；不替代本系统任务成果目录。\n\n【你会得到】操作结果说明；若需留存可写摘要 md。\n\n须交付：Notion协作摘要.md。\n写入系统分配任务目录。\n若该 MCP 未在后台启用或未配置凭据，请明确说明「未启用/未配置」，禁止假装已查到账套数据。",
  "mcp-im-notify": "用「消息通知」向已配置通道发送一条文字（企微/钉钉/WhatsApp）。\n\n【你在做什么】调用出站通知 MCP；未配置时说明需管理员在后台「消息通道」配置。\n\n【请填写】\n- 通道：【企微 / 钉钉 / WhatsApp】\n- 正文：【要发送的内容】\n\n【请准备】需管理员已配置对应通道。\n\n【你会得到】发送成功或失败的简短说明。\n\n须交付：notify-result.md。\n写入系统分配任务目录。",
  "mcp-cn-erp": "用「企业 ERP 查询」帮我查经营数据（订单/库存/应收应付）。\n\n【你在做什么】在已启用且已配置的 ERP（金蝶或用友）中做只读查询，整理成可读摘要。\n\n【请填写】（不知道就写「不清楚」，不要空着）\n- 要查什么：【如：上月应收、低库存、待审销售订单】\n- 时间范围：【如：本月 / 上月】\n- ERP 类型（若已知）：【金蝶 / 用友 / 不清楚】\n\n【请准备】需管理员已启用「企业 ERP 查询」并配置账套凭据；本对话默认只读，不要审批单据。\n\n【你会得到】一份查询摘要（含关键单据号/金额/状态），标明数据来自 ERP 查询而非猜测。\n\n须交付：ERP查询摘要.md。\n写入系统分配任务目录。\n若该 MCP 未在后台启用或未配置凭据，请明确说明「未启用/未配置」，禁止假装已查到账套数据。",
  "mcp-kingdee-k3": "用「金蝶云星空」帮我按单据类型查询或导出单据。\n\n【你在做什么】在只读模式下查询金蝶单据（如销售订单），必要时导出到任务目录。\n\n【请填写】（不知道就写「不清楚」，不要空着）\n- 单据类型/form_id：【如：SAL_SaleOrder / 不清楚】\n- 筛选条件：【如：本月、客户名】\n- 只要摘要还是要导出文件：【摘要 / 导出】\n\n【请准备】需管理员启用「金蝶云星空」且 MCP 为 readonly；禁止保存/审核/下推。\n\n【你会得到】查询结果摘要或任务目录内导出文件路径。\n\n须交付：金蝶单据查询摘要.md。\n写入系统分配任务目录。\n若该 MCP 未在后台启用或未配置凭据，请明确说明「未启用/未配置」，禁止假装已查到账套数据。",
  "mcp-yonyou-fin": "用「用友做账」帮我查凭证、科目或余额表。\n\n【你在做什么】只读查询用友财务账套数据，整理成可读摘要。\n\n【请填写】（不知道就写「不清楚」，不要空着）\n- 要查什么：【凭证列表 / 科目树 / 余额表 / 明细账】\n- 期间：【如：2026-07】\n- 科目或凭证号（可选）：【】\n\n【请准备】需管理员启用「用友做账」并配置凭据；禁止删除凭证或擅自改科目。\n\n【你会得到】财务查询摘要（含关键科目/金额）。\n\n须交付：用友财务查询摘要.md。\n写入系统分配任务目录。\n若该 MCP 未在后台启用或未配置凭据，请明确说明「未启用/未配置」，禁止假装已查到账套数据。",
  "mcp-tax-invoice": "用「数电发票」帮我查询或查验发票（不开票）。\n\n【你在做什么】经已配置的第三方数电发票服务做查询/查验，不代开票、不红冲。\n\n【请填写】（不知道就写「不清楚」，不要空着）\n- 操作：【查询状态 / 查验真伪】\n- 发票号码或税号等要素：【】\n- 开票方名称（可选）：【】\n\n【请准备】需管理员启用「数电发票」并配置商用 Token；开票/红冲默认关闭。\n\n【你会得到】查验或查询结果说明（标明第三方服务）。\n\n须交付：发票查验摘要.md。\n写入系统分配任务目录。\n若该 MCP 未在后台启用或未配置凭据，请明确说明「未启用/未配置」，禁止假装已查到账套数据。",
  "hub-pack-fal-video": "用「Fal多模态视频」帮我：【如：生成一支 10 秒产品短片 / 把这张图变成动态视频 / 批量出 3 版广告素材】（需配置 Fal Key）。可做：文生图、图生视频、口播视频、视频工作流。须交付：*.mp4、storyboard.md。\n\n标准成果清单：\n1. *.mp4\n2. storyboard.md\n写入系统分配任务目录。缺 Key 或外部服务不可用时仍交付 md 说明，勿中断。",
  "hub-pack-threejs": "用「3D网页创作」做一个【产品或场景】的 3D 展示网页：【说明风格与交互，如：可拖拽旋转、滚动驱动动画】。可做：搭场景、调材质灯光、做动画、加交互。",
  "remotion-best-practices": "用「Remotion 最佳实践」帮我：【说明具体场景、目标与必须包含的信息】。",
  "create-frontend-design": "用「前端设计规范」为【页面/组件】给出审美方向与实现建议，避免模板化 UI。",
  "create-ai-video-gen": "用「AI 视频生成工作流」为【产品/主题】生成短视频脚本与分镜（需模型池视频 Key）。",
  "create-ui-ux-pro-max": "用「UI/UX 专业审查」审查【页面或组件描述】，给出可用性与视觉层次改进清单。",
  "mcp-playwright": "用「浏览器自动化 MCP」帮我：【说明要打开的页面或浏览器操作】。",
  "mcp-postgres-readonly": "用「Postgres 只读」帮我查业务库表结构或只读 SQL。\n\n【你在做什么】对客户指定的业务 PostgreSQL 做 schema 探查或 SELECT，禁止写库。\n\n【请填写】（不知道就写「不清楚」，不要空着）\n- 目标：【看表结构 / 跑只读查询】\n- 表名或问题：【如：最近 7 天订单数】\n- 库别名（若有）：【】\n\n【请准备】需管理员启用并配置业务库只读连接串；禁止连接控制面数据库。\n\n【你会得到】查询结果摘要（勿贴密钥）。\n\n须交付：业务库查询摘要.md。\n写入系统分配任务目录。\n若该 MCP 未在后台启用或未配置凭据，请明确说明「未启用/未配置」，禁止假装已查到账套数据。",
  "hub-pack-pm-toolkit": "用「PM工具包」帮我做产品工作：【如：给笔记 App 写 PRD / 排 Q3 路线图 / 做竞品对比】，并附产品背景。可做：PRD、路线图、竞品分析、用户故事、实验设计、GTM。",
  "hub-pack-pm-methods": "用「产品方法论」带我做一次工作坊式拆解：【选一个：机会方案树 / 用户旅程图 / 产品定位 / 用户故事地图】，对象是【产品或业务】。",
  "brainstorm-structured": "用「结构化脑暴（Superpowers）」围绕【主题】带我做一轮分步头脑风暴，最后整理成点子清单。",
  "comp-cashier-ops": "用「财税出纳」帮我把本月「开出去的票、收进来的票、税额」核清楚（不懂财务也能跟着填）。\n\n【你在做什么】用出纳日常语言给出核对步骤与检查表：销项/进项分别看什么、哪些异常要找会计。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 公司名：【如：星河智能杭州有限公司】\n- 所在城市：【如：杭州】\n- 纳税身份：【一般纳税人 / 小规模纳税人】（小规模通常进项税额抵扣规则不同，请如实选）\n- 本月大概情况：【如：开了约 20 张销项票、收到约 15 张进项票；没有数字就写「按常见中小微假设」】\n- 有没有卡住的事：【如：有一张专票备注不对 / 客户迟迟不要票 / 没有】\n\n【请准备】发票汇总表、进项清单截图或税务导出表（可选；没有则按文字做通用核对清单）。\n\n【你会得到】一份可照着执行的《出纳日常核对清单》：每日/每月步骤、异常标记方法、要交给会计的问题清单。\n\n须交付：出纳日常核对清单.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "mcp-cn-central-policy": "用「中央政策 MCP」结构化检索政府网政策列表与正文（需管理员已配置该服务）。\n\n【你在做什么】通过已连接的中央政策服务拉取文件列表/正文要点；若服务未配置，请改用「国家政策检索」卡并说明降级。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 关键词：【如：中小企业发展条例、加计扣除】\n- 只要列表还是要正文摘要：【列表 / 摘要 / 两者】\n- 条数上限：【如：8 条】\n\n【请准备】无需附件。若后台未配置 cn-central-policy，请先让管理员按说明接入，或改点「国家政策检索」。\n\n【你会得到】一份《政策检索摘要》及可核对的来源信息。\n\n须交付：政策检索摘要.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "anth-pptx": "用「PPT幻灯」生成一份可编辑的 PPT 文件：【主题与大纲要点】。须交付：presentation.pptx。\n写入系统分配任务目录。\n【能力】pptx（anth-pptx）\n须交付：presentation.pptx。\n【须交付】presentation.pptx\n【目录】写入系统分配任务目录\n【禁】禁空壳 presentation.pptx；禁白板无风格页",
  "comp-contract-review": "用「商事合同审查」帮我读合同：标出对我方不利的条款，并给出修改方向。\n\n【你在做什么】按商务人员可读的方式做审查意见（付款、违约、责任上限、知识产权、保密等），不是替律师盖章。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 我方角色：【买方 / 卖方 / 服务方 / 客户方】\n- 合同类型：【如：采购合同、SaaS 服务协议、框架协议】\n- 最担心的点：【如：拖延付款、无限责任、数据归属、单方解约】\n- 合同标题或对方名称：【可选】\n\n【请准备】合同全文附件（强烈建议上传 PDF/Word/文本）；没有附件则粘贴关键条款。\n\n【你会得到】一份《合同审查意见书》：红线/黄线清单、建议改法、需法务确认的问题。\n\n须交付：合同审查意见书.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "comp-corp-governance": "用「公司设立与治理」帮我梳理章程与治理要点：股东会、董事/执行董事、重大事项怎么定。\n\n【你在做什么】给中小微股东/创始人一份治理备忘，避免「口头约定、文件对不上」。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 公司类型：【有限责任公司 / 股份公司】\n- 股东人数与大致股权：【如：两人 60/40】\n- 有无董事会：【执行董事 / 董事会 / 不清楚】\n- 最想理清的事：【如：对外担保谁拍板、股权转让限制、分红规则】\n\n【请准备】章程 PDF/Word 或工商底档（可选）。\n\n【你会得到】一份《公司治理与章程要点》：决策事项分层、建议写入章程的条款、待律师确认清单。\n\n须交付：公司治理与章程要点.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "comp-entity-compliance": "用「经营主体合规速查」帮我检查公司执照与经营范围是否「说得通、做得对」。\n\n【你在做什么】对照营业执照、实际业务、公示/年报等，列出中小微常见主体合规风险与自查项。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 公司全称：【如：星河智能（杭州）有限公司】\n- 所在城市：【如：杭州余杭】\n- 主营业务一句话：【如：卖工业软件 SaaS 给工厂】\n- 纳税身份：【一般纳税人 / 小规模纳税人 / 不清楚】\n- 有无分公司/对外投资：【有/无；有则简述】\n\n【请准备】营业执照照片或经营范围文字（可选；没有则按填写内容做）。\n\n【你会得到】一份《经营主体合规检查清单》，含风险点、建议动作与需向工商/会计确认的事项。\n\n须交付：经营主体合规检查清单.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "comp-invoice-vat": "用「发票与增值税要点」帮我用大白话弄懂：什么票能开、进项能不能抵、税率大概怎么看。\n\n【你在做什么】整理中小微最常见的发票合规与增值税注意点，避免「随便开票、乱抵进项」。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 纳税身份：【一般纳税人 / 小规模】\n- 主营开票内容：【如：软件服务、货物销售、混合】\n- 最困惑的问题：【如：招待费发票能否抵扣 / 电子专票怎么入账 / 税率选错怎么办】\n- 公司所在地：【如：广东深圳】\n\n【请准备】问题发票截图或开票品名列表（可选）。\n\n【你会得到】一份《发票与增值税合规要点》：场景对照表、禁忌提示、建议找会计确认的项。\n\n须交付：发票与增值税合规要点.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "comp-labor-hire": "用「劳动合同与录用」帮我检查录用通知/劳动合同：有没有坑、缺不缺法定条款。\n\n【你在做什么】面向人事/老板可读：试用期、工资结构、岗位、保密竞业是否表述清楚，风险点怎么改。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 城市与用工地：【如：杭州】\n- 岗位与用工形式：【全职 / 兼职 / 实习；岗位名】\n- 薪资结构概要：【如：基本工资 + 绩效；试用期比例】\n- 是否要签竞业/保密：【要 / 不要 / 不确定】\n\n【请准备】录用通知或劳动合同草案附件（推荐）；没有则按填写项出审查要点与条款补全建议。\n\n【你会得到】一份《录用审查意见》：问题清单、建议改写要点、入职手续提醒。\n\n须交付：录用审查意见.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "comp-policy-search": "用「国家政策检索」帮我查中央/部委公开政策：用关键词找出相关文件并写摘要。\n\n【你在做什么】优先用已配置的中央政策检索服务；未配置时改为检索政府网公开页，并标明来源链接。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 检索主题：【如：专精特新、研发费用加计扣除、中小微融资担保】\n- 时间范围：【如：近一年 / 近三年】\n- 关注部委：【如：工信部、财政部；可写「不限」】\n- 你要用来做什么：【如：判断能否申报、写内部简报】\n\n【请准备】无需附件；若有内部关键词表可粘贴。管理员未配置 MCP 时仍可检索公开网页。\n\n【你会得到】一份《政策检索摘要》：文件名/文号、要点、适用对象、来源链接与下一步建议。\n\n须交付：政策检索摘要.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "comp-pr-press-release": "用「新闻通稿」帮我写一篇可对外审定的正式新闻稿。\n\n【你在做什么】按「标题—导语—正文—关于公司—媒体联系人」结构起草 Word 通稿，事实可核验、无绝对化违禁用语。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 公司/品牌全称：【】\n- 通稿类型：【新品发布 / 融资 / 合作 / 活动 / 人事 / 其他】\n- 核心消息一句话：【】\n- 希望媒体记住的 3 个要点：【】\n- 禁写或需弱化的内容：【如：未公开财务数据、未证实对比】\n- 目标媒体层级：【央级/行业/地方/科技垂直】\n\n【请准备】已过审事实清单、数据出处、高管引语（可选）；没有则写「按公开信息起草并标注待核实」。\n\n【你会得到】一份正式《新闻通稿》Word（.docx）：含媒体联系人区与待核实标注。\n\n须交付：新闻通稿.docx。\n写入系统分配任务目录。\n产出为公关传播工作底稿，不构成法律意见，亦不代发新闻/代建媒体关系；对外发布前须法务与管理层审定。中国大陆传播语境优先。",
  "comp-tax-sme-hnte": "用「小微与高新优惠」帮我对照：我们依法可能适用哪些税收优惠，还缺什么条件。\n\n【你在做什么】只谈合法优惠与申报准备（禁止筹划逃税、虚开发票、隐瞒收入）。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 企业规模大致：【营收/人数区间即可】\n- 是否高新技术企业或打算认定：【已是 / 打算 / 否】\n- 是否小微企业优惠关注：【是 / 否】\n- 所在省市：【】\n\n【请准备】上年纳税申报表或资质证书名称（可选）。\n\n【你会得到】一份《合法税收优惠对照备忘》：可能适用项、条件缺口、下一步咨询会计/税务所的问题。\n\n须交付：合法税收优惠对照备忘.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "consult-finance": "我是你的企业财务顾问，有什么可以帮您？",
  "cyber-ppt": "用「Cyber 咨询PPT」把【研究报告/业务材料】做成 10 页 MBB 风可编辑 PPTX，SCR 叙事。须交付：presentation.pptx、slide_manifest.json、visual_qa_gate.json。写入系统分配任务目录。禁止 Task/subagent；走 nova-fast-path 快路径，禁止 ImageGen 全页蓝图。\n\n标准成果清单：\n1. presentation.pptx\n2. slide_manifest.json\n3. visual_qa_gate.json",
  "fin-dcf-two-stage": "用「DCF 两阶段估值」帮我：【说明具体场景、目标与必须包含的信息】。",
  "fin-excel-financial-model": "用「Excel 财务模型搭建」帮我：【说明具体场景、目标与必须包含的信息】。",
  "comp-bid-analyze": "用「招标文件解析」帮我把厚厚的招标文件拆成：资格条件、评分、必交材料与澄清点。\n\n【你在做什么】用表格化要点说明「能不能投、怎么得分、缺什么材料」，避免漏读废标条款。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 项目简称：【如：某市政务云运维】\n- 我方大致资质：【如：软件企业、有类似案例 2 个 / 不清楚】\n- 最想先确认的事：【如：有没有注册资金门槛、是否允许联合体】\n\n【请准备】招标文件 PDF/Word（必须尽量上传；过大可先传资格与评分章节）。\n\n【你会得到】一份《招标文件解析报告》：资格门槛、评分要点、废标风险、澄清问题清单。\n\n须交付：招标文件解析报告.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "comp-cit-basics": "用「企税与汇算要点」帮我梳理企业所得税年度汇算大概要准备什么、常见调整项有哪些。\n\n【你在做什么】面向老板/出纳的汇算清缴备忘（不是代替申报软件填表）。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 纳税身份与规模：【小微 / 一般；大概营收区间可写】\n- 会计年度：【如：2025 年度汇算】\n- 是否有亏损弥补、分红、关联交易：【有/无/不清楚】\n- 是否已请代理记账：【是 / 否】\n\n【请准备】利润表/科目余额表截图或代理记账沟通纪要（可选）。\n\n【你会得到】一份《企业所得税申报要点》：时间节奏、资料清单、常见纳税调整提示、风险提醒。\n\n须交付：企业所得税申报要点.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "comp-data-privacy": "用「数据与隐私合规」帮我评估：我们收集用户/员工信息时，有哪些该补的手续与风险。\n\n【你在做什么】用不懂法也能看懂的方式，梳理个人信息收集、共享、跨境与用户权利响应差距。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 产品形态：【如：ToB SaaS / App / 官网表单】\n- 主要收集哪些信息：【如：管理员手机号、员工邮箱、操作日志】\n- 服务器与数据存放：【境内 / 有境外 / 不清楚】\n- 是否把数据给第三方：【如：短信通道、云厂商、广告 SDK；无则写无】\n- 用户能否查改删个人信息：【已支持 / 未支持 / 不清楚】\n\n【请准备】隐私政策链接或正文、产品功能说明（可选；可粘贴关键段落）。\n\n【你会得到】一份《个人信息保护合规评估》草稿：处理目的、合法性基础、差距项与优先补齐建议。\n\n须交付：个人信息保护合规评估.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "comp-pr-media-pitch": "用「媒体 Pitch 包」帮我准备可发给记者的选题与邀约材料。\n\n【你在做什么】输出选题角度、分层媒体清单框架、个性化 Pitch 信模板（不代发邮件）。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 品牌/产品：【】\n- 本次希望被报道的点：【】\n- 目标记者类型：【科技 / 财经 / 消费 / 地方 / 不清楚】\n- 可提供的独家素材：【数据/样机/采访对象/无】\n- 期望发稿时间窗口：【】\n\n【请准备】过往报道链接或竞品报道样例（可选）。\n\n【你会得到】一份《媒体Pitch包》：角度表、媒体分层表（模板）、Pitch 信草稿、跟进节奏建议。\n\n须交付：媒体Pitch包.md。\n写入系统分配任务目录。\n产出为公关传播工作底稿，不构成法律意见，亦不代发新闻/代建媒体关系；对外发布前须法务与管理层审定。中国大陆传播语境优先。",
  "comp-rd-super-deduction": "用「研发加计扣除」帮我列出：要想合规享受加计，资料与费用归集要注意什么。\n\n【你在做什么】资料指引与合规要点（禁止虚构研发费用、伪造辅助账）。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 是否有研发项目：【有项目名更好；无则写「想了解门槛」】\n- 研发人员是否相对固定：【是 / 否 / 不清楚】\n- 费用是否单独归集：【已做辅助账 / 混在一起 / 不清楚】\n- 委托外部研发：【有 / 无】\n\n【请准备】研发项目立项书、费用明细或辅助账样例（可选；敏感数字可打码）。\n\n【你会得到】一份《研发加计扣除资料指引》：资料清单、归集注意点、常见否决风险。\n\n须交付：研发加计扣除资料指引.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "comp-termination": "用「解除终止与补偿」帮我评估这次员工离职/解除：程序对不对、补偿大致怎么估。\n\n【你在做什么】说明协商一致、过失性解除、经济性裁员等路径差异与证据/程序风险（不是代发解除通知）。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 城市：【如：上海】\n- 入职与拟离职时间：【如：2023-03 入职，拟 2026-08 解除】\n- 解除原因一句话：【如：协商一致 / 不能胜任 / 严重违纪 / 合同到期不续】\n- 月工资大致水平：【可写区间；用于补偿估算提示】\n- 是否已有书面证据：【如：警告信、绩效面谈记录；无则写无】\n\n【请准备】劳动合同、解除沟通记录或违纪材料（可选；敏感信息可打码）。\n\n【你会得到】一份《解除终止风险意见》：可选路径、程序步骤提示、补偿估算口径、证据缺口。\n\n须交付：解除终止风险意见.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "mcp-geo-optimizer": "用「GEO Optimizer MCP」帮我：【说明要查的数据或要执行的操作】（需已连接对应服务）。须交付：aeo-audit.md、aeo-audit.html、llms.txt。\n\n标准成果清单：\n1. aeo-audit.md\n2. aeo-audit.html\n3. llms.txt\n写入系统分配任务目录。缺 Key 或外部服务不可用时仍交付 md 说明，勿中断。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "comp-ad-product": "用「广告与产品上线合规」帮我审查广告文案/上线材料，避免绝对化用语与违规承诺。\n\n【你在做什么】对照广告法与上线常见红线，标出违禁表述、需改写的句子，以及上线前建议补的说明。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 投放渠道：【如：微信朋友圈、抖音、官网首页】\n- 产品一句话：【如：AI 财务助手，尚未取得认证】\n- 要审查的文案：【粘贴完整文案；示例：「全国第一，100% 替代会计，稳赚不赔」】\n- 是否已有资质/检测报告：【有则列出名称；无则写无】\n\n【请准备】投放截图、落地页链接或文案附件（推荐上传；没有则按粘贴文案审）。\n\n【你会得到】一份《广告法与上线合规意见》：问题句、改写建议、上线前检查项。\n\n须交付：广告法与上线合规意见.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "comp-bid-write": "用「商务标与技术标」帮我起草投标响应草案：商务标 + 技术标各一份。\n\n【你在做什么】根据招标要求起草可继续润色的标书骨架（非最终盖章件；需对照原招标文件核对）。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 项目简称：【如：某区数字化改造项目】\n- 我方公司名与核心优势：【各写一句】\n- 拟投入的关键人员/产品：【如有】\n- 是否已有招标解析结论：【有则 @ 上一份解析报告；无则说明将按附件招标文件起草】\n\n【请准备】招标文件 +（可选）公司介绍、业绩列表、技术方案提纲。\n\n【你会得到】两份草案：商务标草案、技术标草案，便于团队分工改稿。\n\n须交付：商务标草案.md、技术标草案.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。\n\n标准成果清单：\n1. 商务标草案.md\n2. 技术标草案.md",
  "comp-pr-digital-campaign": "用「数字公关策划」帮我做一套以权威背书/earned media 为主的公关策划。\n\n【你在做什么】规划议题地图、内容资产（通稿/署名/资料包）、渠道节奏与成功指标；不包含付费投放排期。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 业务目标：【提升认知 / 融资背书 / 招聘品牌 / 纠偏舆情 / 其他】\n- 周期：【如：4 周】\n- 主叙事一句话：【】\n- 可用证据：【客户案例/数据/奖项/无】\n- 是否需要 Press Kit 大纲：【是 / 否】\n\n【请准备】品牌简介或官网链接（可选）。\n\n【你会得到】一份《数字公关策划》：议题—资产—节奏—KPI—风险与审批节点。\n\n须交付：数字公关策划.md。\n写入系统分配任务目录。\n产出为公关传播工作底稿，不构成法律意见，亦不代发新闻/代建媒体关系；对外发布前须法务与管理层审定。中国大陆传播语境优先。",
  "create-taste-brutalist": "用「create-taste-brutalist」做【品牌/活动】Brutalist 风官网 landing。须交付 index.html。多页站点时 characters.html 与 index.html 同目录。写入系统分配任务目录；禁止 artifacts/design/ 语义目录；禁止 Task/subagent。须交付：index.html。",
  "viral-article-generator": "用「爆款长文生成」为【选题/行业热点】写一篇公众号气质长文（自动选风，禁问卷）。须交付：article-brief.md、article.md、quotes.md、channel-plan.md。\n写入系统分配任务目录。",
  "comp-pr-crisis-response": "用「危机应对」帮我在突发声誉风险下整理分级研判与应对时间线。\n\n【你在做什么】做严重级别判断、干系人清单、首小时 Holding、24 小时动作与监测阈值；须提示法务会签，不代发声明。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 发生了什么（已知事实）：【】\n- 当前曝光范围：【仅内部 / 社媒小范围 / 媒体已报道 / 不清楚】\n- 已采取措施：【】\n- 受影响方：【客户/员工/投资者/合作伙伴/公众】\n- 是否涉及伤亡、违法违规或监管：【是 / 否 / 不清楚】\n\n【请准备】截图、报道链接、内部通报草稿（可选；敏感信息打码）。\n\n【你会得到】一份《危机应对方案》：分级、Holding 草案、干系人口径、时间线、升级触发条件与复盘清单。\n\n须交付：危机应对方案.md。\n写入系统分配任务目录。\n产出为公关传播工作底稿，不构成法律意见，亦不代发新闻/代建媒体关系；对外发布前须法务与管理层审定。中国大陆传播语境优先。",
  "comp-pr-reputation": "用「声誉修复」帮我制定中长期口碑与负面评价应对计划。\n\n【你在做什么】区分日常口碑运营与危机后修复：监测维度、回复原则、内容补救与信任重建节奏。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 主要负面来源：【电商评论 / 社媒 / 黑猫投诉 / 媒体 / 职场平台 / 混合】\n- 核心指控一句话：【】\n- 是否已有官方回应：【有 / 无】\n- 修复窗口：【2 周 / 1 个月 / 一季度】\n\n【请准备】代表性差评或报道摘要（可选）。\n\n【你会得到】一份《声誉修复计划》：监测框架、回复策略、内容补救、阶段 KPI、勿做清单。\n\n须交付：声誉修复计划.md。\n写入系统分配任务目录。\n产出为公关传播工作底稿，不构成法律意见，亦不代发新闻/代建媒体关系；对外发布前须法务与管理层审定。中国大陆传播语境优先。",
  "create-taste-skill": "用「审美规范」为【产品/品牌】做一页落地页 HTML，Anti-Slop 审美、先输出 Design Read。须交付：index.html。写入系统分配任务目录。",
  "fin-financial-analyst": "用「财务比率与预算差异分析」帮我：【说明具体场景、目标与必须包含的信息】。",
  "comp-pr-spokesperson-qa": "用「发言人口径」帮我准备对外统一说法与记者问答。\n\n【你在做什么】输出 Holding Statement、标准回答、禁区话术与升级转交规则；强调「一个声音」、禁止臆测未核实事实。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 议题/事件：【】\n- 发言人角色：【CEO / PR / 产品负责人 / 其他】\n- 必须说清楚的 3 点：【】\n- 绝对不能说的点：【】\n- 面向：【媒体 / 客户 / 员工 / 全渠道】\n\n【请准备】已确认事实清单（必填；没有则写「仅公开信息，其余标待核实」）。\n\n【你会得到】一份《发言人问答口径》：Holding、FAQ/Q&A、禁区、若追问升级路径。\n\n须交付：发言人问答口径.md。\n写入系统分配任务目录。\n产出为公关传播工作底稿，不构成法律意见，亦不代发新闻/代建媒体关系；对外发布前须法务与管理层审定。中国大陆传播语境优先。",
  "comp-pr-internal-comms": "用「内部沟通通报」帮我写给员工/管理层的对内说明。\n\n【你在做什么】对内口径与对外口径对齐：事实、已采取措施、员工须知、禁止擅自对外发言。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 通报场景：【产品故障 / 舆情事件 / 组织调整 / 安全事件 / 其他】\n- 受众：【全体员工 / 管理层 / 客服一线】\n- 已知事实：【】\n- 员工可以对外说什么：【】\n- 员工禁止做什么：【如：私自发社媒、猜测原因】\n\n【请准备】对外声明草稿或管理层决议要点（可选）。\n\n【你会得到】一份《内部沟通通报》：正文 + 管理层 briefing 要点 + 对内/对外口径对照表。\n\n须交付：内部沟通通报.md。\n写入系统分配任务目录。\n产出为公关传播工作底稿，不构成法律意见，亦不代发新闻/代建媒体关系；对外发布前须法务与管理层审定。中国大陆传播语境优先。",
  "fin-ib-pe-workflow": "用「投行·PE 工作流指南」帮我：【说明具体场景、目标与必须包含的信息】。",
  "comp-zjtx-tech-sme": "用「专精特新与科技型」帮我对照：我们这种企业离专精特新/科技型中小企业差在哪。\n\n【你在做什么】按公开条件做资格对照清单与官方入口提示（不代填申报系统、不伪造材料）。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 企业所在省市：【如：浙江杭州】\n- 所属行业与主营产品：【一句话】\n- 成立年限与员工规模：【如：成立 4 年，约 40 人】\n- 研发人员/研发费用大概情况：【有比例更好；没有写不清楚】\n- 目标资质：【专精特新中小企业 / 科技型中小企业 / 两者都想了解】\n\n【请准备】营业执照、上年度审计或研发费用说明（可选）。\n\n【你会得到】一份《专精特新或科技型对照清单》：条件对照、缺口、建议准备材料与官方入口。\n\n须交付：专精特新或科技型对照清单.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "comp-bookkeeping-xlsx": "用「做账对账台账」帮我搭一份简单的科目说明与对账台账骨架，方便和会计对账。\n\n【你在做什么】用中小微常见科目讲清「钱进钱出记在哪」，并给出可继续填数的台账结构。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 公司名：【】\n- 业务类型：【如：卖软件订阅 + 少量硬件】\n- 记账方式：【自己记 / 代理记账 / 不清楚】\n- 最想理清的账户：【如：公户、微信/支付宝、应收账款】\n\n【请准备】银行流水摘要或现有科目表（可选）；需要 Excel 时可说明「请同时给可编辑表」。\n\n【你会得到】一份《做账对账台账》说明（Markdown）；如你要求可附简易表结构说明。\n\n须交付：做账对账台账.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "comp-handbook-compete": "用「竞业与员工手册」帮我审查员工手册或竞业限制条款是否合理、可执行。\n\n【你在做什么】标出过宽/过严/缺少补偿或公示程序的问题，并给出修改方向。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 审查对象：【员工手册 / 竞业协议 / 两者】\n- 适用岗位：【如：销售、研发核心岗】\n- 竞业补偿是否已约定：【有金额或比例 / 无 / 不清楚】\n- 公司所在地：【如：北京】\n\n【请准备】员工手册或竞业协议附件（推荐上传）。\n\n【你会得到】一份《竞业或手册审查意见》：条款问题、建议改法、落地注意点。\n\n须交付：竞业或手册审查意见.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "comp-local-subsidy": "用「稳岗就业与地方惠企」帮我找【省市】稳岗、就业、惠企补贴该去哪个门户看。\n\n【你在做什么】整理地方政策路径说明与申报入口提示（非代申报；以当地官网最新公告为准）。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 省市：【如：浙江省杭州市】\n- 企业类型：【如：小微企业、科技型】\n- 关心方向：【稳岗返还 / 吸纳就业 / 租金补贴 / 研发资助 / 不限】\n- 当前用工规模：【大概人数即可】\n\n【请准备】无需必传附件；有当地政策截图可上传。\n\n【你会得到】一份《地方惠企政策路径说明》：可能相关的政策类型、查询路径、注意事项。\n\n须交付：地方惠企政策路径说明.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "mcp-ai-seo": "用「AI SEO MCP」帮我：【说明要查的数据或要执行的操作】（需已连接对应服务）。须交付：aeo-page-audit.md、aeo-page-audit.html。\n\n标准成果清单：\n1. aeo-page-audit.md\n2. aeo-page-audit.html\n写入系统分配任务目录。缺 Key 或外部服务不可用时仍交付 md 说明，勿中断。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "mcp-agent-aeo": "用「AgentAEO 监测 MCP」帮我：【说明要查的数据或要执行的操作】（需已连接对应服务）。须交付：monitor-data.json。\n写入系统分配任务目录。缺 Key 或外部服务不可用时仍交付 md 说明，勿中断。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "pmd-finance-metrics-quickref": "用「finance-metrics-quickref」帮我：【说明具体场景、目标与必须包含的信息】。",
  "pmd-tam-sam-som-calculator": "用「tam-sam-som-calculator」帮我：【说明具体场景、目标与必须包含的信息】。",
  "anth-xlsx": "用「Excel表格」做一个 Excel 文件：【数据内容与想要的统计或图表】。须交付：办公格式文件（docx/pptx/xlsx/pdf）。\n写入系统分配任务目录。",
  "consult-tax": "我是你的企业税务顾问，有什么可以帮您？",
  "content-flywheel": "用「content-flywheel」帮我：【说明具体场景、目标与必须包含的信息】。",
  "pmd-saas-economics-efficiency-metrics": "用「saas-economics-efficiency-metrics」帮我：【说明具体场景、目标与必须包含的信息】。",
  "consult-hr": "我是你的企业人力顾问，有什么可以帮您？",
  "pmd-saas-revenue-growth-metrics": "用「saas-revenue-growth-metrics」帮我：【说明具体场景、目标与必须包含的信息】。",
  "consult-legal": "我是你的企业法律顾问，有什么可以帮您？",
  "fin-equity-research-report": "用「AI 股权研究报告」帮我：【说明具体场景、目标与必须包含的信息】。",
  "consult-contract": "我是你的企业合同顾问，有什么可以帮您？",
  "consult-policy": "我是你的企业政策顾问，有什么可以帮您？",
  "ppt-gorden-super": "用「Gorden 超级PPT」把【主题与要点】做成 8 页豪华图片幻灯并还原为可编辑 PPTX。须交付：presentation.pptx、slide-NN.png。写入系统分配任务目录。\n\n标准成果清单：\n1. presentation.pptx\n2. slide-NN.png\n3. slide-manifest.json",
  "fin-relative-valuation": "用「相对估值与可比分析」帮我：【说明具体场景、目标与必须包含的信息】。",
  "fin-sotp-breakup": "用「SOTP 分部估值」帮我：【说明具体场景、目标与必须包含的信息】。",
  "mkt-campaign-budget": "用「活动预算表」做【活动】预算表：渠道、金额、周期与备注，输出 Excel。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "comp-regulatory-lite": "用「监管合规入门」帮我列一张「我们这个行业先要搞清楚什么」的入门自查单。\n\n【你在做什么】按行业整理备案、内容/数据安全等相关官方入口与自查项（不是代做等保测评）。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 行业：【如：互联网信息服务 + 生成式 AI 应用】\n- 服务对象：【企业客户 / 个人用户 / 两者都有】\n- 主体所在城市：【如：上海】\n- 是否已有 ICP/算法/其他备案：【已有写名称；无/不清楚】\n\n【请准备】官网链接或产品简介（可选）。\n\n【你会得到】一份《行业合规入门检查单》：优先事项、官方入口提示、需咨询专业机构的事项。\n\n须交付：行业合规入门检查单.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "comp-subsidy-checklist": "用「申报材料清单助手」帮我列齐某项补贴/资质申报大概要准备哪些材料。\n\n【你在做什么】按常见申报包列材料清单与责任人建议（禁止伪造盖章件；最终以主管部门目录为准）。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 申报项目名称：【如：某市数字化改造补贴 / 科技型中小企业评价】\n- 申报主体：【公司全称】\n- 截止日期：【如知道】\n- 已有材料：【如：营业执照、审计报告；没有写「从零准备」】\n\n【请准备】申报通知 PDF 或官网截图（强烈建议；没有则按项目名做通用清单并标注需核对）。\n\n【你会得到】一份《补贴申报材料清单》：材料表、是否必备、准备提示、常见缺项。\n\n须交付：补贴申报材料清单.md。\n写入系统分配任务目录。\n产出为草稿工作底稿，不构成法律/税务/会计/劳动人事执业意见；落地前须专业审定。中国大陆法域。",
  "pmd-finance-based-pricing-advisor": "用「finance-based-pricing-advisor」帮我：【说明具体场景、目标与必须包含的信息】。",
  "create-taste-brandkit": "用「品牌视觉板」为【品牌名】生成品牌 kit 参考板与色板说明。须交付：brandkit.md。写入系统分配任务目录。",
  "comp-pr-sentiment-brief": "用「舆情简报」帮我汇总近期公开讨论中的品牌声量与风险点。\n\n【你在做什么】基于可联网公开信息做简报（非 7×24 监测平台）；列提及主题、情感倾向、需跟进项。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 监测对象（品牌/产品/高管）：【】\n- 时间范围：【近 7 天 / 近 30 天】\n- 关注渠道：【新闻 / 社媒 / 评论 / 全部公开】\n- 特别关键词：【】\n\n【请准备】已知负面链接（可选）。\n\n【你会得到】一份《舆情简报》：摘要、主题簇、风险分级、建议动作；无法核实处标明「公开信息有限」。\n\n须交付：舆情简报.md。\n写入系统分配任务目录。\n产出为公关传播工作底稿，不构成法律意见，亦不代发新闻/代建媒体关系；对外发布前须法务与管理层审定。中国大陆传播语境优先。",
  "create-taste-imagegen-web": "用「网页参考板」为【产品】生成 3 屏网页 UI 参考图板 prompt 与说明。须交付：web-moodboard.md。写入系统分配任务目录。",
  "create-taste-imagegen-mobile": "用「create-taste-imagegen-mobile」帮我：【说明具体场景、目标与必须包含的信息】。",
  "comp-pr-media-day-kit": "用「媒体日执行包」帮我准备发布会/场馆媒体日的执行材料。\n\n【你在做什么】输出流程单、邀请要点、现场物料清单、媒体 Q&A 与当天应急要点（不做活动搭建施工图）。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 活动形式：【发布会 / 媒体开放日 / 圆桌 / 线上发布】\n- 日期与城市：【】\n- 核心发布内容：【】\n- 预计媒体规模：【】\n- 是否有产品演示/试乘试用：【是 / 否】\n\n【请准备】日程草案或场地限制（可选）。\n\n【你会得到】一份《媒体日执行包》：倒排期、邀请话术要点、物料清单、现场 Q&A、应急联系人表。\n\n须交付：媒体日执行包.md。\n写入系统分配任务目录。\n产出为公关传播工作底稿，不构成法律意见，亦不代发新闻/代建媒体关系；对外发布前须法务与管理层审定。中国大陆传播语境优先。",
  "create-taste-image-to-code": "用「create-taste-image-to-code」帮我：【说明具体场景、目标与必须包含的信息】。",
  "comp-pr-thought-leadership": "用「思想领导力稿」帮我起草高管/专家署名文章或演讲提纲。\n\n【你在做什么】形成可投行业媒体或自有渠道的观点稿；要求有独特判断与可核验论据，避免空泛口号。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 署名人角色：【CEO / CTO / 业务负责人】\n- 议题领域：【】\n- 核心主张一句话：【】\n- 目标刊登类型：【行业媒体署名 / 公司博客 / 演讲】\n- 字数偏好：【1500 / 2500 / 提纲即可】\n\n【请准备】可用数据、案例或过往演讲提纲（可选）。\n\n【你会得到】一份《思想领导力署名稿》（全文或详细提纲）+ 建议投放媒体类型。\n\n须交付：思想领导力署名稿.md。\n写入系统分配任务目录。\n产出为公关传播工作底稿，不构成法律意见，亦不代发新闻/代建媒体关系；对外发布前须法务与管理层审定。中国大陆传播语境优先。",
  "create-taste-redesign": "用「站点改版审美」审计并改版【页面 URL 或描述】，保留品牌资产。须交付：index.html。写入系统分配任务目录。",
  "ppt-gorden-image-gen": "用「Gorden 图片PPT」生成 6 页【主题】豪华高密度图片型幻灯。须交付：slide-NN.png、presentation.pptx。写入系统分配任务目录。\n\n标准成果清单：\n1. slide-NN.png\n2. presentation.pptx",
  "comp-pr-esg-narrative": "用「ESG 传播叙事」帮我梳理可对外讲的责任与可持续发展故事。\n\n【你在做什么】输出主叙事、证据锚点、渠道建议与「防漂绿」禁区；不替代正式 ESG 报告鉴证。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 企业类型：【制造业 / 互联网 / 消费 / 其他】\n- 已有实践：【环保/员工/治理/公益，分点写】\n- 是否已有正式 ESG/社会责任报告：【有 / 无】\n- 传播目的：【招投标加分 / 品牌 / 出海 / 投资者沟通】\n\n【请准备】报告摘要或关键数据（可选；禁止编造未发生的减排/捐赠数据）。\n\n【你会得到】一份《ESG传播叙事》：故事线、证据清单、渠道、禁区话术与待核实项。\n\n须交付：ESG传播叙事.md。\n写入系统分配任务目录。\n产出为公关传播工作底稿，不构成法律意见，亦不代发新闻/代建媒体关系；对外发布前须法务与管理层审定。中国大陆传播语境优先。",
  "pmd-company-research": "用「company-research」帮我：【说明具体场景、目标与必须包含的信息】。",
  "ppt-gorden-image2pptx": "用「Gorden 图转PPT」把【artifacts 内 slide PNG 路径】四层拆解为可编辑 PPTX。须交付：presentation.pptx。写入系统分配任务目录。",
  "comp-pr-ir-messaging": "用「投资者沟通口径」帮我准备融资/业绩相关的对外说法要点。\n\n【你在做什么】仅做传播口径与 FAQ，不写招股书、不替代信披与财务模型；敏感数字必须来自用户提供。\n\n【请填写】（不知道就写「不清楚」或「按常见中小微假设」，不要空着）\n- 场景：【融资发布 / 业绩沟通 / 战略升级说明 / 传闻澄清】\n- 可公开的关键事实：【】\n- 绝对不能透露：【】\n- 受众：【投资人 / 分析师 / 员工 / 媒体】\n\n【请准备】已公开新闻稿或董事会决议摘要（可选）。\n\n【你会得到】一份《投资者沟通口径》：核心信息、FAQ、禁区、与正式信披衔接提示。\n\n须交付：投资者沟通口径.md。\n写入系统分配任务目录。\n产出为公关传播工作底稿，不构成法律意见，亦不代发新闻/代建媒体关系；对外发布前须法务与管理层审定。中国大陆传播语境优先。",
  "pmd-business-health-diagnostic": "用「business-health-diagnostic」帮我：【说明具体场景、目标与必须包含的信息】。",
  "mkt-claude-seo": "用「seo」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。\nGEO 报告/分析类：须先 write_file 完成同名 .md 并 read_file 确认，再生成同名 .html；禁止未写 MD 先写 HTML。",
  "fin-regtech-compliance-brief": "用「RegTech 合规要点简报」帮我：【说明具体场景、目标与必须包含的信息】。",
  "fin-yfinance-market-data": "用「公开市场数据抓取」帮我：【说明具体场景、目标与必须包含的信息】。",
  "pmd-feature-investment-advisor": "用「feature-investment-advisor」帮我：【说明具体场景、目标与必须包含的信息】。",
  "create-taste-minimalist": "用「create-taste-minimalist」帮我：【说明具体场景、目标与必须包含的信息】。",
  "pmd-pestel-analysis": "用「pestel-analysis」帮我：【说明具体场景、目标与必须包含的信息】。",
  "create-taste-soft": "用「create-taste-soft」帮我：【说明具体场景、目标与必须包含的信息】。",
  "create-taste-stitch": "用「create-taste-stitch」帮我：【说明具体场景、目标与必须包含的信息】。",
  "create-taste-output": "用「create-taste-output」帮我：【说明具体场景、目标与必须包含的信息】。",
  "create-vid-scriptwriting": "用「程序化视频脚本」为【产品】做 30 秒产品演示 YAML 脚本：场景、帧数、旁白与动效说明。须交付：分镜.md、script.md。\n\n标准成果清单：\n1. 分镜.md\n2. script.md\n写入系统分配任务目录。",
  "hf-hyperframes": "用「HTML 代码做视频」做一支【时长】视频：【画面与节奏，如：标题淡入 + 背景视频 + 轻音乐】。须交付：promo.mp4。\n写入系统分配任务目录。缺视频/HyperFrames Key 时须温和说明缺依赖并停止无限补齐，勿用 HTML 录屏假绿充数。\n【能力】hf-hyperframes（hf-hyperframes）\n须交付：promo.mp4。\n【须交付】promo.mp4\n【目录】写入系统分配任务目录\n【禁】禁 generate_video 冒充 render_hyperframes",
  "create-vid-saas-demo-script": "用「SaaS 演示分镜」为【SaaS 产品】写 60 秒功能演示逐镜分镜与 Remotion 时间轴。须交付：分镜.md、script.md。\n\n标准成果清单：\n1. 分镜.md\n2. script.md\n写入系统分配任务目录。",
  "hf-product-launch-video": "用「hf-product-launch-video」：【说明视频目标、时长与风格】。须交付：promo.mp4。\n写入系统分配任务目录。缺视频/HyperFrames Key 时须温和说明缺依赖并停止无限补齐，勿用 HTML 录屏假绿充数。\n【能力】hf-product-launch-video（hf-product-launch-video）\n须交付：promo.mp4。\n【须交付】promo.mp4\n【目录】写入系统分配任务目录\n【禁】禁 generate_video 冒充 HyperFrames",
  "persona-buffett": "用「巴菲特思维」帮我评估：【贴上你的投资或商业决策】，从护城河、现金流与长期价值给判断。",
  "create-vid-seedance-prompt": "用「即梦分镜提示」为【主题】写 15 秒 Seedance 2.0 分镜提示词（含 @引用说明）。须交付：03-seedance-prompts.md。\n写入系统分配任务目录。缺视频/HyperFrames Key 时须温和说明缺依赖并停止无限补齐，勿用 HTML 录屏假绿充数。",
  "hf-motion-graphics": "用「hf-motion-graphics」：【说明视频目标、时长与风格】。须交付：promo.mp4。\n写入系统分配任务目录。缺视频/HyperFrames Key 时须温和说明缺依赖并停止无限补齐，勿用 HTML 录屏假绿充数。",
  "persona-duan-yongping": "用「段永平思维」帮我判断这个生意：【描述商业模式】，看它是否本分、能否长期赚钱。",
  "persona-steve-jobs": "用「乔布斯思维」帮我打磨：【产品或方案】，从核心体验与发布叙事给出尖锐意见。",
  "create-vid-seedance-codec": "用「即梦相机分镜」为【主题】规划 25 格分镜与长片分段策略（相机四维编码）。须交付：分镜.md、script.md。\n\n标准成果清单：\n1. 分镜.md\n2. script.md\n写入系统分配任务目录。缺视频/HyperFrames Key 时须温和说明缺依赖并停止无限补齐，勿用 HTML 录屏假绿充数。",
  "hf-general-video": "用「hf-general-video」：【说明视频目标、时长与风格】。须交付：promo.mp4。\n写入系统分配任务目录。缺视频/HyperFrames Key 时须温和说明缺依赖并停止无限补齐，勿用 HTML 录屏假绿充数。",
  "mkt-brand-video": "用「品牌视频分镜」为【产品】做 15 秒品牌宣传片分镜（6–8 镜头），含旁白与画面说明。须交付：storyboard.md。\n写入系统分配任务目录。",
  "persona-elon-musk": "用「马斯克思维」用第一性原理拆解：【问题，如某项成本或技术路线】，找出突破口。",
  "persona-munger": "用「芒格思维」检查这个计划：【贴方案】，找出认知偏误与逆向风险。",
  "create-vid-visual-prompt": "用「影视镜头策划」把下面剧本拆成 14 字段镜头卡并写 Seedance 提示词：【粘贴剧本或梗概】。须交付：01-shot-cards.md。\n写入系统分配任务目录。",
  "hf-faceless-explainer": "用「hf-faceless-explainer」：【说明视频目标、时长与风格】。须交付：promo.mp4。\n写入系统分配任务目录。缺视频/HyperFrames Key 时须温和说明缺依赖并停止无限补齐，勿用 HTML 录屏假绿充数。",
  "mkt-dmp-video-script": "用「营销视频脚本」为【产品】写一条 60 秒抖音营销视频脚本：3 秒 hook 与时间轴。须交付：02-script-timed.md。\n写入系统分配任务目录。",
  "create-vid-director": "用「AI 导演分镜」以王家卫风格为【故事梗概】写镜头表与 keyframe 提示。须交付：02-director-board.md。\n写入系统分配任务目录。",
  "hf-slideshow": "用「hf-slideshow」：【说明视频目标、时长与风格】。须交付：hf-project/index.html。\n写入系统分配任务目录。缺视频/HyperFrames Key 时须温和说明缺依赖并停止无限补齐，勿用 HTML 录屏假绿充数。",
  "persona-feynman": "用「费曼思维」帮我真正搞懂：【概念或知识点】，讲到我能复述给别人听。",
  "create-vid-storyboard-pack": "用「连续性分镜包」为【广告创意】输出 continuity 分镜包：bible、镜头卡、交接矩阵。须交付：continuity_bible.md、shot_cards.md、handoff_design_matrix.md。\n\n标准成果清单：\n1. continuity_bible.md\n2. shot_cards.md\n3. handoff_design_matrix.md\n写入系统分配任务目录。",
  "hf-website-to-video": "用「网站一键成片」抓取【网址】，自动产出一支【时长，如 25 秒】品牌宣传视频。须交付：promo.mp4。\n写入系统分配任务目录。缺视频/HyperFrames Key 时须温和说明缺依赖并停止无限补齐，勿用 HTML 录屏假绿充数。\n【能力】hf-website-to-video（hf-website-to-video）\n须交付：promo.mp4。\n【须交付】promo.mp4\n【目录】写入系统分配任务目录\n【禁】禁 generate_video 冒充 HyperFrames；禁 HTML 录屏假视频",
  "persona-naval": "用「纳瓦尔思维」帮我设计个人杠杆路径：【你的职业现状与目标】。",
  "create-vid-seedance-series": "用「短剧分镜生成」把下面故事改编为四幕短剧剧本并写第 1 集 Seedance 分镜：【粘贴故事】。须交付：分镜.md、script.md。\n\n标准成果清单：\n1. 分镜.md\n2. script.md\n写入系统分配任务目录。缺视频/HyperFrames Key 时须温和说明缺依赖并停止无限补齐，勿用 HTML 录屏假绿充数。",
  "persona-taleb": "用「塔勒布思维」评估：【策略或计划】在极端情况下是否反脆弱，给加固建议。",
  "create-vid-viral-copy": "用「爆款视频文案」为【产品】写 3 条 30 秒爆款短视频口播脚本（含 hook）。须交付：01-hooks.md。\n写入系统分配任务目录。",
  "persona-zizek": "用「齐泽克思维」审视这份方案：【贴方案】，找出没明说但默认成立的前提。",
  "persona-trump": "用「特朗普思维」帮我设计这场谈判：【对手与目标】，给开场姿态与让步节奏。",
  "persona-zhang-yiming": "用「张一鸣思维」帮我梳理：【产品或团队问题】，给迭代优先级与组织建议。",
  "remotion-video": "用「React 程序化视频」搭一个【用途】视频模板：【要参数化的内容，如标题与数字】，方便批量渲染。须交付：03/out.mp4、Remotion 工程目录。\n\n标准成果清单：\n1. 03/out.mp4\n2. Remotion 工程目录\n写入系统分配任务目录。",
  "edu-sci-timesfm-forecasting": "用「时序预测 TimesFM」帮我：【说明具体场景、目标与必须包含的信息】。须交付：forecast.json 或 forecast.csv、forecast.png。\n\n标准成果清单：\n1. forecast.json 或 forecast.csv\n2. forecast.png\n写入系统分配任务目录。",
  "diagram-maker": "用「图表制作」把下面的内容画成图：【粘贴流程、结构或数据，并说明想要的图类型】。",
  "mkt-campaign-plan": "用「活动全案」写【活动，如 618 大促】完整方案：目标、人群、渠道、内容日历与 KPI。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-campaign-report": "用「结案报告」把这次活动整理成结案报告（PDF 或 Word）：【粘贴活动数据与亮点】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-ab-test-plan": "用「ab-test-plan」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-ad-creative": "用「ad-creative」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-add-integration": "用「add-integration」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-aeo-audit": "用「aeo-audit」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-aeo-geo": "用「aeo-geo」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-agency-dashboard": "用「agency-dashboard」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-analytics-insights": "用「analytics-insights」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-anomaly-scan": "用「anomaly-scan」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-attribution-model": "用「attribution-model」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-attribution-report": "用「attribution-report」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-audience-intelligence": "用「audience-intelligence」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-audience-profile": "用「audience-profile」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-autopilot-status": "用「autopilot-status」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-backlink-gap": "用「backlink-gap」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-brand-setup": "用「brand-setup」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-budget-optimizer": "用「budget-optimizer」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-budget-tracker": "用「budget-tracker」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-c2pa-metadata": "用「c2pa-metadata」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-campaign-audit": "用「campaign-audit」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-campaign-orchestrator": "用「campaign-orchestrator」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-campaign-plan": "用「campaign-plan」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-campaign-status": "用「campaign-status」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-case-study-plan": "用「case-study-plan」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-check": "用「check」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-churn-risk": "用「churn-risk」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-client-onboarding": "用「client-onboarding」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-client-proposal": "用「client-proposal」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-client-report": "用「client-report」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-client-validation-document": "用「client-validation-document」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-cohort-analysis": "用「cohort-analysis」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-competitor-alerts": "用「competitor-alerts」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-competitor-analysis": "用「competitor-analysis」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-competitor-monitor": "用「competitor-monitor」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-competitor-pages": "用「competitor-pages」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-connect": "用「connect」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-content-brief": "用「content-brief」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-content-calendar": "用「content-calendar」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-content-decay-scan": "用「content-decay-scan」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-content-engine": "用「content-engine」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-content-repurpose": "用「content-repurpose」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-context-engine": "用「context-engine」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-continuous-improvement-loop": "用「continuous-improvement-loop」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-counter-narrative": "用「counter-narrative」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-cowork-setup": "用「cowork-setup」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-creative-health": "用「creative-health」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-creative-testing-framework": "用「creative-testing-framework」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-credential-switch": "用「credential-switch」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-crm-sync": "用「crm-sync」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-cro": "用「cro」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-dark-funnel": "用「dark-funnel」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-data-export": "用「data-export」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-data-import": "用「data-import」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-email-sequence": "用「email-sequence」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-emerging-channels": "用「emerging-channels」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-engagement-workflow": "用「engagement-workflow」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-entity-audit": "用「entity-audit」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-eval-config": "用「eval-config」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-eval-content": "用「eval-content」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-eval-suite": "用「eval-suite」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-exec-summary": "用「exec-summary」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-executive-dashboard": "用「executive-dashboard」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-focus-group": "用「focus-group」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-four-core-documents": "用「four-core-documents」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-funnel-architect": "用「funnel-architect」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-funnel-audit": "用「funnel-audit」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-geo-monitor": "用「geo-monitor」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-growth-engineering": "用「growth-engineering」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-growth-plan": "用「growth-plan」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-gsc-ai-performance": "用「gsc-ai-performance」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-help": "用「help」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-hreflang-check": "用「hreflang-check」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-image-seo-audit": "用「image-seo-audit」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-import-guidelines": "用「import-guidelines」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-import-sop": "用「import-sop」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-import-template": "用「import-template」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-influencer-brief": "用「influencer-brief」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-influencer-creator": "用「influencer-creator」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-integrations": "用「integrations」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-intelligence-report": "用「intelligence-report」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-journey-design": "用「journey-design」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-keyword-cluster": "用「keyword-cluster」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-keyword-research": "用「keyword-research」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-landing-page-audit": "用「landing-page-audit」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-language-audit": "用「language-audit」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-language-config": "用「language-config」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-launch-ad-campaign": "用「launch-ad-campaign」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-launch-campaign": "用「launch-campaign」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-launch-plan": "用「launch-plan」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-lead-import": "用「lead-import」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-learn": "用「learn」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-live-dashboard": "用「live-dashboard」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-local-seo": "用「local-seo」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-local-seo-audit": "用「local-seo-audit」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-localize-campaign": "用「localize-campaign」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-loop-detect": "用「loop-detect」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-market-weather": "用「market-weather」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-marketing-automation": "用「marketing-automation」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-martech-audit": "用「martech-audit」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-media-plan": "用「media-plan」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-message-test": "用「message-test」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-multilingual-score": "用「multilingual-score」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-narrative-landscape": "用「narrative-landscape」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-narrative-tracker": "用「narrative-tracker」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-page-seo-analysis": "用「page-seo-analysis」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-paid-advertising": "用「paid-advertising」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-pdf-report": "用「pdf-report」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-performance-check": "用「performance-check」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-performance-report": "用「performance-report」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-pipeline-update": "用「pipeline-update」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-pricing-test": "用「pricing-test」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-programmatic-seo": "用「programmatic-seo」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-prompt-test": "用「prompt-test」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-publish-blog": "用「publish-blog」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-qbr-plan": "用「qbr-plan」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-quality-report": "用「quality-report」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-rank-monitor": "用「rank-monitor」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-recall": "用「recall」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-redirect-manager": "用「redirect-manager」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-region-config": "用「region-config」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-retargeting-strategy": "用「retargeting-strategy」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-review-response": "用「review-response」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-roi-calculator": "用「roi-calculator」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-save-knowledge": "用「save-knowledge」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-schedule-social": "用「schedule-social」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-search-knowledge": "用「search-knowledge」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-segment-audience": "用「segment-audience」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-send-email-campaign": "用「send-email-campaign」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-send-notification": "用「send-notification」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-send-report": "用「send-report」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-send-sms": "用「send-sms」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-seo-audit": "用「seo-audit」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-seo-drift": "用「seo-drift」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-seo-implement": "用「seo-implement」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-seo-plan": "用「seo-plan」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-serp-tracker": "用「serp-tracker」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-share-of-voice": "用「share-of-voice」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-simulate": "用「simulate」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-sitemap-manager": "用「sitemap-manager」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-social-strategy": "用「social-strategy」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-sop-library": "用「sop-library」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-status": "用「status」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-switch-brand": "用「switch-brand」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-sync-memory": "用「sync-memory」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-team-assign": "用「team-assign」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-tech-seo-audit": "用「tech-seo-audit」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-technical-seo": "用「technical-seo」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-translate-content": "用「translate-content」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-validate-output": "用「validate-output」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-validate-profile": "用「validate-profile」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-verify-claims": "用「verify-claims」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-webinar-plan": "用「webinar-plan」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-what-if": "用「what-if」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-dmp-yearly-planner": "用「yearly-planner」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-email-bible": "用「email-marketing-bible」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-go-live-checklist": "用「上线检查清单」为【网站或产品】出发布前核对清单：SEO、结构化数据与渠道就绪。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-last30days": "用「last30days」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-pitch-deck": "用「比稿演示稿」做一份 10 页可编辑 PPT：主题【提案主题】，用于【客户提案或内部汇报】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-screenshots": "用「mkt-screenshots」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-strategy-deck": "用「策略汇报 PPT」把【策略方案】整理成 12 页可汇报演示稿：【粘贴方案要点】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-typefully": "用「mkt-typefully」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-typefully-typefully": "用「typefully」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-x-article-publisher": "用「x-article-publisher」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-ooh-strategy": "用「户外媒介策略」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-produce-ooh": "用「户外创意制作」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-ooh-traffic-checklist": "用「上刊监播清单」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-claude-ads": "用「Claude 投放助手」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "mkt-cn-ads-skills": "用「国内投放助手」帮我：【说明具体场景、目标与必须包含的信息】。须交付：marketing-deliverable.md。\n写入系统分配任务目录。",
  "anth-canvas-design": "用「视觉画布设计」设计一张【海报或封面】：【主题、文字内容与风格】。须交付：办公格式文件（docx/pptx/xlsx/pdf）。\n写入系统分配任务目录。",
  "anth-mcp-builder": "用「MCP构建」帮我搭一个 MCP 服务：【要接入的数据或工具】，写好代码并调通。须交付：办公格式文件（docx/pptx/xlsx/pdf）。\n写入系统分配任务目录。缺 Key 或外部服务不可用时仍交付 md 说明，勿中断。",
  "create-ai-music": "用「AI音乐」帮我写一首歌：【主题、风格、时长】，输出歌词与编曲说明。",
  "create-color-expert": "用「配色专家」给【品牌或界面】出 3 套配色方案，附色值与使用场景。",
  "create-nanobanana-ppt": "用「AI 配图幻灯」把【主题】做成每页带 AI 配图的幻灯片。",
  "create-ui-baseline-ui": "用「UI基线」为【产品】生成一套 UI 组件基线：按钮、表单、卡片与颜色变量。",
  "create-ui-fixing-accessibility": "用「无障碍修复」检查并修复这个页面的无障碍问题：【贴代码或页面路径】。",
  "create-ui-fixing-metadata": "用「页面元数据优化」补全这个页面的 title、description 与社交分享卡片：【页面路径或 URL】。",
  "create-ui-fixing-motion-performance": "用「动效性能优化」排查这个页面动画卡顿并优化：【页面路径或问题描述】。",
  "create-ui-ui-skills-root": "用「ui-skills-root」帮我：【说明具体场景、目标与必须包含的信息】。",
  "create-wonda": "用「wonda」帮我创作：【说明需求】。",
  "create-youtube-clipper": "用「YouTube 剪辑」处理这个视频：【粘贴 YouTube 链接】，分析章节后剪出精彩片段并配中英字幕。",
  "dev-next-best-practices": "用「Next.js 实践」审查或搭建我的 Next.js 项目：【项目路径或需求】。",
  "dev-playwright": "用「浏览器自动化」帮我：【写 E2E 测试 / 自动化操作某网页，说明目标】。",
  "dev-sentry-sdk-setup": "用「Sentry 接入」给【项目路径】接入 Sentry 错误监控并验证上报。",
  "edu-recursive-research": "用「教育调研」帮我调研：【教育相关主题】，多轮检索后给结构化报告。",
  "edu-tutor-skills": "用「家教技能」当我的一对一家教：【年级 + 科目 + 今天要解决的问题】。",
  "humanizer": "用「去AI味润色」改写下面这段文字，让它读起来像真人写的：【粘贴文字】。",
  "meeting-recorder-assistant": "用「meeting-recorder-assistant」帮我：【说明具体场景、目标与必须包含的信息】。",
  "office-ecom": "用「电商助手」处理电商运营任务：【商品文案 / listing 优化 / 活动方案】。",
  "office-epub": "用「电子书制作」把【文稿或章节目录】打包成 EPUB 电子书。",
  "office-nutrient": "用「文档API」处理文档：【转换 / 合并 / 加水印等，说明文件与目标格式】（需 Nutrient Key）。",
  "pd-document-export": "用「pd-document-export」帮我：【说明具体场景、目标与必须包含的信息】。",
  "unslop": "用「去八股润色」修改下面的文字，去掉排比堆叠、套话开头和空洞词：【粘贴文字】。",
  "video-db-python": "用「视频库检索」把视频上传到 VideoDB 并按内容搜索片段：【视频来源与要找的内容】（需 VideoDB Key）。",
  "karpathy-guidelines": "用「AI 编码规范」审查【代码文件或目录】，按减少 AI 编码失误的准则列出问题与改法。",
  "minimax-pdf": "用「高视觉质量 PDF」把【内容或文稿】排版成设计感强的 PDF 报告。"
};

export function getTryPromptZh(slug, displayName = '') {
  const direct = TRY_PROMPT_ZH[slug];
  if (direct) return direct;
  const name = (displayName || slug).trim();
  return `用「${name}」帮我：【说明具体场景、目标与必须包含的信息】。`;
}

export function assertTryPromptQuality() {
  const bad = [];
  for (const [slug, text] of Object.entries(TRY_PROMPT_ZH)) {
    for (const reason of hubPromptQualityIssues(text)) {
      bad.push({ slug, reason });
    }
  }
  if (bad.length > 0) {
    throw new Error(`try-prompt quality: ${bad.length} issue(s): ${bad.slice(0, 5).map((b) => `${b.slug}(${b.reason})`).join(', ')}`);
  }
  return bad;
}
