/**
 * Chinese labels for Phuryn PM (pms-*) and Dean Peters (pmd-*) skill tails.
 * PD-SAAS-FORK
 */

/** @type {Record<string, string>} */
const TAIL_ZH = {
  // pms-*
  'swot-analysis': 'SWOT分析',
  'ab-test-analysis': 'A/B测试分析',
  'analyze-feature-requests': '功能需求分析',
  'ansoff-matrix': '安索夫矩阵',
  'beachhead-segment': '滩头细分',
  'brainstorm-experiments-existing': '存量实验设计',
  'brainstorm-experiments-new': '新品实验设计',
  'brainstorm-ideas-existing': '存量创意脑暴',
  'brainstorm-ideas-new': '新品创意脑暴',
  'brainstorm-okrs': 'OKR脑暴',
  'business-model': '商业模式',
  'cohort-analysis': '队列分析',
  'competitive-battlecard': '竞争战卡',
  'competitor-analysis': '竞品分析',
  'create-prd': 'PRD撰写',
  'customer-journey-map': '用户旅程图',
  'draft-nda': 'NDA起草',
  'dummy-dataset': '样例数据集',
  'grammar-check': '语法检查',
  'growth-loops': '增长飞轮',
  'gtm-motions': 'GTM打法',
  'gtm-strategy': 'GTM策略',
  'ideal-customer-profile': '理想客户画像',
  'identify-assumptions-existing': '存量假设识别',
  'identify-assumptions-new': '新品假设识别',
  'intended-vs-implemented': '预期与实现',
  'interview-script': '访谈脚本',
  'job-stories': '工作故事',
  'lean-canvas': '精益画布',
  'market-segments': '市场细分',
  'market-sizing': '市场规模',
  'marketing-ideas': '营销点子',
  'metrics-dashboard': '指标看板',
  'monetization-strategy': '变现策略',
  'north-star-metric': '北极星指标',
  'opportunity-solution-tree': '机会方案树',
  'outcome-roadmap': '成果路线图',
  'pestle-analysis': 'PESTLE分析',
  'porters-five-forces': '五力模型',
  'positioning-ideas': '定位创意',
  'pre-mortem': '预演复盘',
  'pricing-strategy': '定价策略',
  'prioritization-frameworks': '优先级框架',
  'prioritize-assumptions': '假设优先级',
  'prioritize-features': '功能优先级',
  'privacy-policy': '隐私政策',
  'product-name': '产品起名',
  'product-strategy': '产品战略',
  'product-vision': '产品愿景',
  'release-notes': '发布说明',
  retro: '复盘会',
  'review-resume': '简历评审',
  'sentiment-analysis': '情感分析',
  'shipping-artifacts': '成果清单',
  'sprint-plan': 'Sprint规划',
  'sql-queries': 'SQL查询',
  'stakeholder-map': '干系人地图',
  'startup-canvas': '创业画布',
  'strategy-red-team': '策略红队',
  'summarize-interview': '访谈摘要',
  'summarize-meeting': '会议纪要',
  'test-scenarios': '测试场景',
  'user-personas': '用户画像',
  'user-segmentation': '用户分群',
  'user-stories': '用户故事',
  'value-prop-statements': '价值主张陈述',
  'value-proposition': '价值主张',
  wwas: 'WWAS框架',

  // pmd-*
  'acquisition-channel-advisor': '获客渠道顾问',
  'ai-shaped-readiness-advisor': 'AI就绪顾问',
  'altitude-horizon-framework': '高度视野框架',
  'business-health-diagnostic': '业务健康诊断',
  'company-research': '公司调研',
  'context-engineering-advisor': '上下文工程顾问',
  'customer-journey-mapping-workshop': '旅程工作坊',
  'director-readiness-advisor': '总监就绪顾问',
  'discovery-interview-prep': '发现访谈准备',
  'discovery-process': '发现流程',
  'eol-message': '下线沟通',
  'epic-breakdown-advisor': '史诗拆解顾问',
  'epic-hypothesis': '史诗假设',
  'executive-onboarding-playbook': '高管入职手册',
  'feature-investment-advisor': '功能投资顾问',
  'finance-based-pricing-advisor': '财务定价顾问',
  'finance-metrics-quickref': '财务指标速查',
  'jobs-to-be-done': 'JTBD框架',
  'lean-ux-canvas': '精益UX画布',
  'organic-growth-advisor': '有机增长顾问',
  'pestel-analysis': 'PESTEL分析',
  'pm-skill-creator': 'PM技能创作',
  'pol-probe': 'POL探针',
  'pol-probe-advisor': 'POL探针顾问',
  'positioning-statement': '定位陈述',
  'positioning-workshop': '定位工作坊',
  'prd-development': 'PRD开发',
  'press-release': '新闻稿',
  'prioritization-advisor': '优先级顾问',
  'problem-framing-canvas': '问题框架画布',
  'problem-statement': '问题陈述',
  'product-sense-interview-answer': '产品感面试',
  'product-strategy-session': '产品战略会',
  'proto-persona': '原型画像',
  'recommendation-canvas': '推荐画布',
  'roadmap-planning': '路线图规划',
  'saas-economics-efficiency-metrics': 'SaaS效率指标',
  'saas-revenue-growth-metrics': 'SaaS增长指标',
  'skill-authoring-workflow': '技能编写流程',
  storyboard: '故事板',
  'tam-sam-som-calculator': 'TAM/SAM/SOM',
  'user-story': '用户故事',
  'user-story-mapping': '用户故事地图',
  'user-story-mapping-workshop': '故事地图工坊',
  'user-story-splitting': '故事拆分',
  'vp-cpo-readiness-advisor': 'VP就绪顾问',
  'workshop-facilitation': '工作坊引导',
};

export function pmPackTailZh(tail) {
  if (!tail) return '';
  if (TAIL_ZH[tail]) return TAIL_ZH[tail];
  return tail.replace(/-/g, ' ');
}
