-- PD-SAAS-FORK: user workspace registry + sync job metadata (file storage Phase 1)

CREATE TABLE IF NOT EXISTS user_workspaces (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    workspace_uuid TEXT NOT NULL,
    legacy_project_id TEXT NOT NULL,
    display_name TEXT NOT NULL,
    storage_kind TEXT NOT NULL DEFAULT 'local',
    local_root_path TEXT,
    canonical_project_key TEXT NOT NULL,
    origin_device_id TEXT,
    sync_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (tenant_id, user_id, workspace_uuid),
    UNIQUE (tenant_id, user_id, legacy_project_id)
);

CREATE INDEX IF NOT EXISTS idx_user_workspaces_user ON user_workspaces(user_id);
CREATE INDEX IF NOT EXISTS idx_user_workspaces_tenant ON user_workspaces(tenant_id);
CREATE INDEX IF NOT EXISTS idx_user_workspaces_legacy ON user_workspaces(legacy_project_id);

CREATE TABLE IF NOT EXISTS storage_sync_jobs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id INTEGER NOT NULL REFERENCES user_workspaces(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'pending',
    bytes_synced INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_storage_sync_jobs_workspace ON storage_sync_jobs(workspace_id);
