-- PD-SAAS-FORK: SaaS conversation directory catalog (distinct from JWT sessions table)

CREATE TABLE IF NOT EXISTS conversation_catalog (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    workspace_id INTEGER REFERENCES user_workspaces(id) ON DELETE SET NULL,
    session_id TEXT NOT NULL,
    legacy_project_id TEXT NOT NULL,
    transcript_rel_path TEXT NOT NULL,
    transcript_abs_hash TEXT,
    workspace_uuid TEXT,
    title TEXT,
    ai_title TEXT,
    custom_title TEXT,
    summary TEXT,
    first_prompt TEXT,
    tag TEXT,
    message_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_activity_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    purge_pending BOOLEAN NOT NULL DEFAULT FALSE,
    status TEXT NOT NULL DEFAULT 'active',
    kind TEXT,
    source TEXT NOT NULL DEFAULT 'web',
    transcript_uri TEXT,
    UNIQUE (tenant_id, user_id, session_id)
);

CREATE INDEX IF NOT EXISTS idx_conversation_catalog_user_active
    ON conversation_catalog (tenant_id, user_id, last_activity_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_conversation_catalog_project_active
    ON conversation_catalog (tenant_id, user_id, legacy_project_id, last_activity_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_conversation_catalog_purge
    ON conversation_catalog (purge_pending, updated_at)
    WHERE purge_pending = TRUE AND deleted_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS conversation_catalog_path_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_id INTEGER NOT NULL REFERENCES conversation_catalog(id) ON DELETE CASCADE,
    old_transcript_rel_path TEXT NOT NULL,
    new_transcript_rel_path TEXT NOT NULL,
    reason TEXT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_conversation_catalog_path_history_catalog
    ON conversation_catalog_path_history (catalog_id, changed_at DESC);

CREATE TABLE IF NOT EXISTS conversation_catalog_outbox (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    session_id TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    next_retry_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_conversation_catalog_outbox_retry
    ON conversation_catalog_outbox (next_retry_at, attempts);
