-- PD-SAAS-FORK (P0-2): server-anchored cold-resume guard state.
-- Persistent per-(session, turn) idempotency + crash-loop budget + recency pointer so that
-- cold reconnect / full-stack restart can safely auto-resume an interrupted turn exactly once,
-- without retry storms across refreshes / multiple tabs / crash loops. Pure new table; never
-- alters existing tables, so rolling back to an older app version leaves it inert.

CREATE TABLE IF NOT EXISTS cold_resume_guard (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL,
    turn_id TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_fired_at TIMESTAMPTZ,
    last_activity_at TIMESTAMPTZ,
    last_progress_ptr TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (tenant_id, user_id, session_id, turn_id)
);

CREATE INDEX IF NOT EXISTS idx_cold_resume_guard_session
    ON cold_resume_guard (tenant_id, user_id, session_id);
